var _yt_www={};(function(g){var window=this;var baa,caa,qa,Ba,ab,kaa,bb,cb,db,eb,jb,laa,kb,maa,naa,rb,Cb,Rb,oc,uaa,vaa,taa,Tc,Uc,$c,bd,yaa,gd,kd,ed,cd,Aaa,jd,hd,id,md,zaa,rd,Baa,Caa,Eaa,Ld,Nd,Od,Pd,be,pe,Gaa,ze,Ge,Fe,Iaa,Jaa,He,Ie,Ke,Laa,Oe,Ue,Te,Pe,Ye,Qaa,bf,Ze,$e,Paa,ef,df,gf,Se,Me,Le,Ne,hf,We,ff,Xe,kf,Saa,Oaa,qf,rf,uf,xf,zf,Nf,Of,Pf,Sf,Uf,Vf,Wf,Zf,Yf,ag,Xf,bg,Qf,Tf,bba,cg,dg,cba,dba,jg,lg,ng,fba,ug,vg,yg,wg,gba,Fg,Mg,Lg,hba,Pg,nba,mba,lba,Vg,kba,iba,jba,oba,bh,pba,ch,eh,qba,rba,fh,gh,lh,ph,qh,rh,uh,vh,wh,xba,yba,mh,oh,kh,wba,nh,Cba,Bba,
Dh,Eh,Aba,Dba,Eba,Fh,Gh,oa,aaa;g.ca=function(a){return function(){return g.aa[a].apply(this,arguments)}};
g.da=function(a){return void 0!==a};
g.n=function(a,b,c){a=a.split(".");c=c||g.m;a[0]in c||!c.execScript||c.execScript("var "+a[0]);for(var d;a.length&&(d=a.shift());)!a.length&&g.da(b)?c[d]=b:c[d]?c=c[d]:c=c[d]={}};
g.q=function(a,b){for(var c=a.split("."),d=b||g.m,e;e=c.shift();)if(null!=d[e])d=d[e];else return null;return d};
g.ea=function(){};
g.fa=function(a){a.getInstance=function(){return a.uc?a.uc:a.uc=new a}};
g.ga=function(a){var b=typeof a;if("object"==b)if(a){if(a instanceof Array)return"array";if(a instanceof Object)return b;var c=Object.prototype.toString.call(a);if("[object Window]"==c)return"object";if("[object Array]"==c||"number"==typeof a.length&&"undefined"!=typeof a.splice&&"undefined"!=typeof a.propertyIsEnumerable&&!a.propertyIsEnumerable("splice"))return"array";if("[object Function]"==c||"undefined"!=typeof a.call&&"undefined"!=typeof a.propertyIsEnumerable&&!a.propertyIsEnumerable("call"))return"function"}else return"null";
else if("function"==b&&"undefined"==typeof a.call)return"object";return b};
g.ha=function(a){return"array"==g.ga(a)};
g.ia=function(a){var b=g.ga(a);return"array"==b||"object"==b&&"number"==typeof a.length};
g.ja=function(a){return"string"==typeof a};
g.ka=function(a){return"number"==typeof a};
g.ma=function(a){return"function"==g.ga(a)};
g.na=function(a){var b=typeof a;return"object"==b&&null!=a||"function"==b};
g.pa=function(a){return a[oa]||(a[oa]=++aaa)};
baa=function(a,b,c){return a.call.apply(a.bind,arguments)};
caa=function(a,b,c){if(!a)throw Error();if(2<arguments.length){var d=Array.prototype.slice.call(arguments,2);return function(){var c=Array.prototype.slice.call(arguments);Array.prototype.unshift.apply(c,d);return a.apply(b,c)}}return function(){return a.apply(b,arguments)}};
g.r=function(a,b,c){g.r=Function.prototype.bind&&-1!=Function.prototype.bind.toString().indexOf("native code")?baa:caa;return g.r.apply(null,arguments)};
g.t=function(a,b){var c=Array.prototype.slice.call(arguments,1);return function(){var b=c.slice();b.push.apply(b,arguments);return a.apply(this,b)}};
g.v=function(a,b){function c(){}
c.prototype=b.prototype;a.L=b.prototype;a.prototype=new c;a.prototype.constructor=a;a.eV=function(a,c,f){for(var k=Array(arguments.length-2),l=2;l<arguments.length;l++)k[l-2]=arguments[l];return b.prototype[c].apply(a,k)}};
qa=function(a){qa[" "](a);return a};
g.ra=function(a,b){try{return qa(a[b]),!0}catch(c){}return!1};
g.sa=function(a,b,c){return Object.prototype.hasOwnProperty.call(a,b)?a[b]:a[b]=c(b)};
g.ta=function(a){if(Error.captureStackTrace)Error.captureStackTrace(this,g.ta);else{var b=Error().stack;b&&(this.stack=b)}a&&(this.message=String(a))};
g.ua=function(a,b){return 0==a.lastIndexOf(b,0)};
g.va=function(a){return/^[\s\xa0]*$/.test(a)};
g.wa=function(a){return(0,window.encodeURIComponent)(String(a))};
g.xa=function(a){if(!daa.test(a))return a;-1!=a.indexOf("&")&&(a=a.replace(eaa,"&amp;"));-1!=a.indexOf("<")&&(a=a.replace(faa,"&lt;"));-1!=a.indexOf(">")&&(a=a.replace(gaa,"&gt;"));-1!=a.indexOf('"')&&(a=a.replace(haa,"&quot;"));-1!=a.indexOf("'")&&(a=a.replace(iaa,"&#39;"));-1!=a.indexOf("\x00")&&(a=a.replace(jaa,"&#0;"));return a};
g.ya=function(a,b){return-1!=a.indexOf(b)};
g.za=function(a){return null==a?"":String(a)};
g.Ca=function(a,b){for(var c=0,d=(0,g.Aa)(String(a)).split("."),e=(0,g.Aa)(String(b)).split("."),f=Math.max(d.length,e.length),k=0;0==c&&k<f;k++){var l=d[k]||"",p=e[k]||"";do{l=/(\d*)(\D*)(.*)/.exec(l)||["","","",""];p=/(\d*)(\D*)(.*)/.exec(p)||["","","",""];if(0==l[0].length&&0==p[0].length)break;c=Ba(0==l[1].length?0:(0,window.parseInt)(l[1],10),0==p[1].length?0:(0,window.parseInt)(p[1],10))||Ba(0==l[2].length,0==p[2].length)||Ba(l[2],p[2]);l=l[3];p=p[3]}while(0==c)}return c};
Ba=function(a,b){return a<b?-1:a>b?1:0};
g.Da=function(a){for(var b=0,c=0;c<a.length;++c)b=31*b+a.charCodeAt(c)>>>0;return b};
g.Ga=function(a,b,c){b=g.Ea(a,b,c);return 0>b?null:g.ja(a)?a.charAt(b):a[b]};
g.Ea=function(a,b,c){for(var d=a.length,e=g.ja(a)?a.split(""):a,f=0;f<d;f++)if(f in e&&b.call(c,e[f],f,a))return f;return-1};
g.Ia=function(a,b){return 0<=(0,g.Ha)(a,b)};
g.Ka=function(a,b){var c=(0,g.Ha)(a,b),d;(d=0<=c)&&g.Ja(a,c);return d};
g.Ja=function(a,b){return 1==Array.prototype.splice.call(a,b,1).length};
g.La=function(a){var b=a.length;if(0<b){for(var c=Array(b),d=0;d<b;d++)c[d]=a[d];return c}return[]};
g.Ma=function(a){return function(){return a}};
g.Na=function(a,b,c){for(var d in a)b.call(c,a[d],d,a)};
g.Pa=function(a){var b=[],c=0,d;for(d in a)b[c++]=d;return b};
g.Qa=function(a,b,c){for(var d in a)if(b.call(c,a[d],d,a))return d};
g.Ra=function(a){for(var b in a)return!1;return!0};
g.Sa=function(a,b){b in a&&delete a[b]};
g.Ta=function(a,b,c){if(null!==a&&b in a)throw Error('The object already contains the key "'+b+'"');a[b]=c};
g.Ua=function(a){var b={},c;for(c in a)b[c]=a[c];return b};
g.Wa=function(a,b){for(var c,d,e=1;e<arguments.length;e++){d=arguments[e];for(c in d)a[c]=d[c];for(var f=0;f<Va.length;f++)c=Va[f],Object.prototype.hasOwnProperty.call(d,c)&&(a[c]=d[c])}};
g.Ya=function(a){return g.ya(g.Xa,a)};
g.Za=function(){return g.Ya("Trident")||g.Ya("MSIE")};
g.$a=function(){return(g.Ya("Chrome")||g.Ya("CriOS"))&&!g.Ya("Edge")};
ab=function(a){g.m.setTimeout(function(){throw a;},0)};
kaa=function(){var a=g.m.MessageChannel;"undefined"===typeof a&&"undefined"!==typeof window&&window.postMessage&&window.addEventListener&&!g.Ya("Presto")&&(a=function(){var a=window.document.createElement("IFRAME");a.style.display="none";a.src="";window.document.documentElement.appendChild(a);var b=a.contentWindow,a=b.document;a.open();a.write("");a.close();var c="callImmediate"+Math.random(),d="file:"==b.location.protocol?"*":b.location.protocol+"//"+b.location.host,a=(0,g.r)(function(a){if(("*"==
d||a.origin==d)&&a.data==c)this.port1.onmessage()},this);
b.addEventListener("message",a,!1);this.port1={};this.port2={postMessage:function(){b.postMessage(c,d)}}});
if("undefined"!==typeof a&&!g.Za()){var b=new a,c={},d=c;b.port1.onmessage=function(){if(g.da(c.next)){c=c.next;var a=c.Ep;c.Ep=null;a()}};
return function(a){d.next={Ep:a};d=d.next;b.port2.postMessage(0)}}return"undefined"!==typeof window.document&&"onreadystatechange"in window.document.createElement("SCRIPT")?function(a){var b=window.document.createElement("SCRIPT");
b.onreadystatechange=function(){b.onreadystatechange=null;b.parentNode.removeChild(b);b=null;a();a=null};
window.document.documentElement.appendChild(b)}:function(a){g.m.setTimeout(a,0)}};
bb=function(a,b,c){this.F=c;this.B=a;this.D=b;this.C=0;this.A=null};
cb=function(a,b){a.D(b);a.C<a.F&&(a.C++,b.next=a.A,a.A=b)};
db=function(){this.C=this.A=null};
eb=function(){this.next=this.scope=this.Bc=null};
jb=function(a,b){fb||laa();gb||(fb(),gb=!0);var c=hb,d=ib.get();d.set(a,b);c.C?c.C.next=d:c.A=d;c.C=d};
laa=function(){if(g.m.Promise&&g.m.Promise.resolve){var a=g.m.Promise.resolve(void 0);fb=function(){a.then(kb)}}else fb=function(){var a=kb;
!g.ma(g.m.setImmediate)||g.m.Window&&g.m.Window.prototype&&!g.Ya("Edge")&&g.m.Window.prototype.setImmediate==g.m.setImmediate?(lb||(lb=kaa()),lb(a)):g.m.setImmediate(a)}};
kb=function(){for(var a;a=hb.remove();){try{a.Bc.call(a.scope)}catch(b){ab(b)}cb(ib,a)}gb=!1};
g.mb=function(){this.Nd=this.Nd;this.Jb=this.Jb};
g.pb=function(a,b){g.nb(a,g.t(g.ob,b))};
g.nb=function(a,b){a.Nd?g.da(void 0)?b.call(void 0):b():(a.Jb||(a.Jb=[]),a.Jb.push(g.da(void 0)?(0,g.r)(b,void 0):b))};
g.ob=function(a){a&&"function"==typeof a.dispose&&a.dispose()};
g.qb=function(a){g.mb.call(this);this.D=1;this.C=[];this.B=0;this.A=[];this.sd={};this.F=!!a};
maa=function(a,b,c){jb(function(){a.apply(b,c)})};
g.tb=function(a){rb(g.sb,arguments)};
g.x=function(a,b){return a in g.sb?g.sb[a]:b};
g.vb=function(a,b){g.ma(a)&&(a=g.ub(a));return window.setTimeout(a,b)};
g.wb=function(a,b){g.ma(a)&&(a=g.ub(a));return window.setInterval(a,b)};
g.xb=function(a){window.clearTimeout(a)};
g.yb=function(a){window.clearInterval(a)};
g.ub=function(a){return a&&window.yterr?function(){try{return a.apply(this,arguments)}catch(b){throw g.zb(b),b;}}:a};
g.zb=function(a,b,c,d,e){var f=g.q("yt.logging.errors.log");f?f(a,b,c,d,e):(f=g.x("ERRORS",[]),f.push([a,b,c,d,e]),g.tb("ERRORS",f))};
naa=function(a,b,c,d,e){var f=!1;if(g.sb.Po&&g.sb.Po.log_window_onerror_fraction&&Math.random()<g.sb.Po.log_window_onerror_fraction)f=!0;else for(var k=window.document.getElementsByTagName("script"),l=0,p=k.length;l<p;l++)if(0<k[l].src.indexOf("/debug-")){f=!0;break}f&&(e||(e=Error(),e.message=a,e.fileName=b,e.lineNumber=c,(0,window.isNaN)(d)||(e.columnNumber=d)),g.zb(e))};
g.Bb=function(a){return a in g.Ab};
rb=function(a,b){if(1<b.length){var c=b[0];a[c]=b[1]}else{var d=b[0];for(c in d)a[c]=d[c]}};
g.y=function(a,b,c){var d=Cb();if(d){var e=d.subscribe(a,function(){if(!Db||Db!=e){var d=arguments,k;k=function(){Eb[e]&&b.apply(c||window,d)};
try{Fb[a]?k():g.vb(k,0)}catch(l){g.zb(l)}}},c);
Eb[e]=!0;Gb[a]||(Gb[a]=[]);Gb[a].push(e);return e}return 0};
g.Hb=function(a){var b=Cb();b&&("number"==typeof a?a=[a]:"string"==typeof a&&(a=[(0,window.parseInt)(a,10)]),(0,g.z)(a,function(a){b.unsubscribeByKey(a);delete Eb[a]}))};
g.A=function(a,b){var c=Cb();return c?c.publish.apply(c,arguments):!1};
g.Ib=function(a,b){Fb[a]=!0;var c=Cb(),c=c?c.publish.apply(c,arguments):!1;Fb[a]=!1;return c};
Cb=function(){return g.q("yt.pubsub.instance_")};
g.Jb=function(){return!!g.q("yt.scheduler.instance")};
g.Kb=function(a,b){(0,window.isNaN)(b)&&(b=void 0);var c=g.q("yt.scheduler.instance.addJob");return c?c(a,1,b):void 0===b?(a(),window.NaN):g.vb(a,b||0)};
g.Lb=function(a,b){return g.Kb(a,b)};
g.Mb=function(a){if(!(0,window.isNaN)(a)){var b=g.q("yt.scheduler.instance.cancelJob");b?b(a):g.xb(a)}};
g.Nb=function(a){for(var b=0,c=a.length;b<c;b++)g.Mb(a[b])};
g.Ob=function(a,b,c,d,e){this.name=a;this.deps=b||[];this.page=c||"";this.H=d?g.ub(d):null;this.F=e?g.ub(e):null;this.D=[];this.A=this.C=0};
g.Pb=function(a){g.Mb(a.C);a.C=g.Lb((0,g.r)(a.init,a))};
g.Sb=function(a){a.name in Qb&&Rb(a.name);Qb[a.name]={reqs:[],disable:(0,g.r)(a.disable,a)};(0,g.z)(a.deps,function(b){if(!(b in Qb))throw Error("Module "+b+" required by "+a.name);Qb[b].reqs.push(a.name)});
a.enable()};
Rb=function(a){if(a in Qb){var b=Qb[a];(0,g.z)(b.reqs,function(a){Rb(a)});
try{b.disable()}catch(c){}delete Qb[a]}};
g.Ub=function(){this.A="";this.C=g.Tb};
g.Vb=function(a){var b=new g.Ub;b.A=a;return b};
g.Xb=function(){this.A="";this.C=Wb};
g.Yb=function(a){if(a instanceof g.Xb&&a.constructor===g.Xb&&a.C===Wb)return a.A;g.ga(a);return"type_error:SafeUrl"};
g.$b=function(a){if(a instanceof g.Xb)return a;a=a.Sf?a.Se():String(a);oaa.test(a)||(a="about:invalid#zClosurez");return g.Zb(a)};
g.Zb=function(a){var b=new g.Xb;b.A=a;return b};
g.dc=function(){this.A="";this.B=g.cc;this.C=null};
g.ec=function(a,b){var c=new g.dc;c.A=a;c.C=b;return c};
g.fc=function(a,b){var c;c=b instanceof g.Xb?b:g.$b(b);a.href=g.Yb(c)};
g.B=function(a,b){return a?a.dataset?a.dataset[g.gc(b)]:a.getAttribute("data-"+b):null};
g.gc=function(a){return hc[a]||(hc[a]=String(a).replace(/\-([a-z])/g,function(a,c){return c.toUpperCase()}))};
g.jc=function(a,b){var c=g.ic(a);window.spf.script.load(a,c,b)};
g.ic=function(a){var b="";if(a){var c=a.indexOf("jsbin/"),d=a.lastIndexOf(".js"),e=c+6;-1<c&&-1<d&&d>e&&(b=a.substring(e,d),b=b.replace(paa,""),b=b.replace(qaa,""),b=b.replace("debug-",""),b=b.replace("tracing-",""))}return b};
g.kc=function(a){if(a.classList)return a.classList;a=a.className;return g.ja(a)&&a.match(/\S+/g)||[]};
g.C=function(a,b){return a.classList?a.classList.contains(b):g.Ia(g.kc(a),b)};
g.lc=function(a,b){this.x=g.da(a)?a:0;this.y=g.da(b)?b:0};
g.mc=function(a,b){this.width=a;this.height=b};
g.nc=function(){return g.Ya("iPhone")&&!g.Ya("iPod")&&!g.Ya("iPad")};
oc=function(){var a=g.m.document;return a?a.documentMode:void 0};
g.qc=function(a){return g.sa(raa,a,function(){return 0<=g.Ca(g.pc,a)})};
g.sc=function(a){return Number(g.rc)>=a};
g.D=function(a){return g.ja(a)?window.document.getElementById(a):a};
g.tc=function(a){return g.ja(a)?window.document.getElementById(a):a};
g.vc=function(a,b){g.Na(b,function(b,d){"style"==d?a.style.cssText=b:"class"==d?a.className=b:"for"==d?a.htmlFor=b:uc.hasOwnProperty(d)?a.setAttribute(uc[d],b):g.ua(d,"aria-")||g.ua(d,"data-")?a.setAttribute(d,b):a[d]=b})};
g.xc=function(a){return g.wc(a||window)};
g.wc=function(a){a=a.document;a=g.yc(a)?a.documentElement:a.body;return new g.mc(a.clientWidth,a.clientHeight)};
g.Ac=function(a){var b=g.zc(a);a=a.parentWindow||a.defaultView;return g.E&&g.qc("10")&&a.pageYOffset!=b.scrollTop?new g.lc(b.scrollLeft,b.scrollTop):new g.lc(a.pageXOffset||b.scrollLeft,a.pageYOffset||b.scrollTop)};
g.zc=function(a){return a.scrollingElement?a.scrollingElement:!g.Bc&&g.yc(a)?a.documentElement:a.body||a.documentElement};
g.Dc=function(a,b,c){return g.Cc(window.document,arguments)};
g.Cc=function(a,b){var c=String(b[0]),d=b[1];if(!saa&&d&&(d.name||d.type)){c=["<",c];d.name&&c.push(' name="',g.xa(d.name),'"');if(d.type){c.push(' type="',g.xa(d.type),'"');var e={};g.Wa(e,d);delete e.type;d=e}c.push(">");c=c.join("")}c=a.createElement(c);d&&(g.ja(d)?c.className=d:g.ha(d)?c.className=d.join(" "):g.vc(c,d));2<b.length&&g.Ec(a,c,b,2);return c};
g.Ec=function(a,b,c,d){function e(c){c&&b.appendChild(g.ja(c)?a.createTextNode(c):c)}
for(;d<c.length;d++){var f=c[d];!g.ia(f)||g.na(f)&&0<f.nodeType?e(f):(0,g.z)(taa(f)?g.La(f):f,e)}};
g.yc=function(a){return"CSS1Compat"==a.compatMode};
g.Fc=function(a){for(var b;b=a.firstChild;)a.removeChild(b)};
g.Gc=function(a,b){b.parentNode&&b.parentNode.insertBefore(a,b)};
g.Hc=function(a,b){b.parentNode&&b.parentNode.insertBefore(a,b.nextSibling)};
uaa=function(a){if(!a)return null;if(a.firstChild)return a.firstChild;for(;a&&!a.nextSibling;)a=a.parentNode;return a?a.nextSibling:null};
vaa=function(a){if(!a)return null;if(!a.previousSibling)return a.parentNode;for(a=a.previousSibling;a&&a.lastChild;)a=a.lastChild;return a};
g.Ic=function(a){return 9==a.nodeType?a:a.ownerDocument||a.document};
taa=function(a){if(a&&"number"==typeof a.length){if(g.na(a))return"function"==typeof a.item||"string"==typeof a.item;if(g.ma(a))return"function"==typeof a.item}return!1};
g.Jc=function(a,b,c,d){c||(a=a.parentNode);for(c=0;a&&(null==d||c<=d);){if(b(a))return a;a=a.parentNode;c++}return null};
g.Lc=function(a){var b=a.__yt_uid_key;b||(b=Kc(),a.__yt_uid_key=b);return b};
g.Mc=function(a){var b=a.cloneNode(!1);"TR"==b.tagName||"SELECT"==b.tagName?(0,g.z)(a.childNodes,function(a){b.appendChild(g.Mc(a))}):b.innerHTML=a.innerHTML;
return b};
g.Nc=function(){var a=window.document;if("visibilityState"in a)return a.visibilityState;var b=waa+"VisibilityState";if(b in a)return a[b]};
g.Oc=function(a){return g.x("EXPERIMENT_FLAGS",{})[a]};
g.Pc=function(a){return/^\s*$/.test(a)?!1:/^[\],:{}\s\u2028\u2029]*$/.test(a.replace(/\\["\\\/bfnrtu]/g,"@").replace(/(?:"[^"\\\n\r\u2028\u2029\x00-\x08\x0a-\x1f]*"|true|false|null|-?\d+(?:\.\d*)?(?:[eE][+\-]?\d+)?)[\s\u2028\u2029]*(?=:|,|]|}|$)/g,"]").replace(/(?:^|:|,)(?:[\s\u2028\u2029]*\[)+/g,""))};
g.Qc=function(a){a=String(a);if(g.Pc(a))try{return eval("("+a+")")}catch(b){}throw Error("Invalid JSON string: "+a);};
g.Sc=function(a,b){return(new g.Rc(b)).Tb(a)};
g.Rc=function(a){this.A=a};
Tc=function(a,b,c){if(null==b)c.push("null");else{if("object"==typeof b){if(g.ha(b)){var d=b;b=d.length;c.push("[");for(var e="",f=0;f<b;f++)c.push(e),e=d[f],Tc(a,a.A?a.A.call(d,String(f),e):e,c),e=",";c.push("]");return}if(b instanceof String||b instanceof Number||b instanceof Boolean)b=b.valueOf();else{c.push("{");f="";for(d in b)Object.prototype.hasOwnProperty.call(b,d)&&(e=b[d],"function"!=typeof e&&(c.push(f),Uc(d,c),c.push(":"),Tc(a,a.A?a.A.call(b,d,e):e,c),f=","));c.push("}");return}}switch(typeof b){case "string":Uc(b,
c);break;case "number":c.push((0,window.isFinite)(b)&&!(0,window.isNaN)(b)?String(b):"null");break;case "boolean":c.push(String(b));break;case "function":c.push("null");break;default:throw Error("Unknown type: "+typeof b);}}};
Uc=function(a,b){b.push('"',a.replace(xaa,function(a){var b=Vc[a];b||(b="\\u"+(a.charCodeAt(0)|65536).toString(16).substr(1),Vc[a]=b);return b}),'"')};
g.Wc=function(a){a.prototype.then=a.prototype.then;a.prototype.$goog_Thenable=!0};
g.Xc=function(a){if(!a)return!1;try{return!!a.$goog_Thenable}catch(b){return!1}};
g.Zc=function(a,b){this.A=0;this.K=void 0;this.D=this.C=this.B=null;this.F=this.H=!1;if(a!=g.ea)try{var c=this;a.call(b,function(a){g.Yc(c,2,a)},function(a){g.Yc(c,3,a)})}catch(d){g.Yc(this,3,d)}};
$c=function(){this.next=this.context=this.C=this.B=this.A=null;this.D=!1};
bd=function(a,b,c){var d=ad.get();d.B=a;d.C=b;d.context=c;return d};
yaa=function(a,b,c){cd(a,b,c,null)||jb(g.t(b,a))};
g.dd=function(a){return new g.Zc(function(b,c){var d=a.length,e=[];if(d)for(var f=function(a,c){d--;e[a]=c;0==d&&b(e)},k=function(a){c(a)},l=0,p;l<a.length;l++)p=a[l],yaa(p,g.t(f,l),k);
else b(e)})};
g.fd=function(a,b){ed(a,null,b,void 0)};
gd=function(a,b){if(0==a.A)if(a.B){var c=a.B;if(c.C){for(var d=0,e=null,f=null,k=c.C;k&&(k.D||(d++,k.A==a&&(e=k),!(e&&1<d)));k=k.next)e||(f=k);e&&(0==c.A&&1==d?gd(c,b):(f?(d=f,d.next==c.D&&(c.D=d),d.next=d.next.next):hd(c),id(c,e,3,b)))}a.B=null}else g.Yc(a,3,b)};
kd=function(a,b){a.C||2!=a.A&&3!=a.A||jd(a);a.D?a.D.next=b:a.C=b;a.D=b};
ed=function(a,b,c,d){var e=bd(null,null,null);e.A=new g.Zc(function(a,k){e.B=b?function(c){try{var e=b.call(d,c);a(e)}catch(u){k(u)}}:a;
e.C=c?function(b){try{var e=c.call(d,b);!g.da(e)&&b instanceof g.ld?k(b):a(e)}catch(u){k(u)}}:k});
e.A.B=a;kd(a,e);return e.A};
g.Yc=function(a,b,c){0==a.A&&(a===c&&(b=3,c=new TypeError("Promise cannot resolve to itself")),a.A=1,cd(c,a.R,a.Y,a)||(a.K=c,a.A=b,a.B=null,jd(a),3!=b||c instanceof g.ld||zaa(a,c)))};
cd=function(a,b,c,d){if(a instanceof g.Zc)return kd(a,bd(b||g.ea,c||null,d)),!0;if(g.Xc(a))return a.then(b,c,d),!0;if(g.na(a))try{var e=a.then;if(g.ma(e))return Aaa(a,e,b,c,d),!0}catch(f){return c.call(d,f),!0}return!1};
Aaa=function(a,b,c,d,e){function f(a){l||(l=!0,d.call(e,a))}
function k(a){l||(l=!0,c.call(e,a))}
var l=!1;try{b.call(a,k,f)}catch(p){f(p)}};
jd=function(a){a.H||(a.H=!0,jb(a.G,a))};
hd=function(a){var b=null;a.C&&(b=a.C,a.C=b.next,b.next=null);a.C||(a.D=null);return b};
id=function(a,b,c,d){if(3==c&&b.C&&!b.D)for(;a&&a.F;a=a.B)a.F=!1;if(b.A)b.A.B=null,md(b,c,d);else try{b.D?b.B.call(b.context):md(b,c,d)}catch(e){nd.call(null,e)}cb(ad,b)};
md=function(a,b,c){2==b?a.B.call(a.context,c):a.C&&a.C.call(a.context,c)};
zaa=function(a,b){a.F=!0;jb(function(){a.F&&nd.call(null,b)})};
g.ld=function(a){g.ta.call(this,a)};
g.od=function(){return{apiaryHost:g.x("APIARY_HOST",void 0),np:g.x("APIARY_HOST_FIRSTPARTY",void 0),gapiHintOverride:g.x("GAPI_HINT_OVERRIDE"),gapiHintParams:g.x("GAPI_HINT_PARAMS",void 0),innertubeApiKey:g.x("INNERTUBE_API_KEY",void 0),innertubeApiVersion:g.x("INNERTUBE_API_VERSION",void 0),SD:g.x("INNERTUBE_CONTEXT_CLIENT_NAME","WEB"),innertubeContextClientVersion:g.x("INNERTUBE_CONTEXT_CLIENT_VERSION",void 0),UD:g.x("INNERTUBE_CONTEXT_HL",void 0),TD:g.x("INNERTUBE_CONTEXT_GL",void 0),eP:g.x("XHR_APIARY_HOST",
void 0)}};
g.pd=function(a){a={client:{hl:a.UD,gl:a.TD,clientName:a.SD,clientVersion:a.innertubeContextClientVersion}};g.x("DELEGATED_SESSION_ID")&&(a.user={onBehalfOfUser:g.x("DELEGATED_SESSION_ID")});return a};
rd=function(){this.A=g.od();qd||(qd=Baa(this.A))};
Baa=function(a){return(new g.Zc(function(b){g.jc(g.x("GAPI_LOADER_URL",void 0),function(){try{g.q("yt.gapi.load")("client",{gapiHintOverride:a.gapiHintOverride,_c:{jsl:{h:a.gapiHintParams}},callback:b})}catch(c){g.zb(c)}})})).then(function(){})};
Caa=function(a,b,c,d){var e={path:"/youtubei/"+a.A.innertubeApiVersion+"/"+b,headers:{"X-Goog-Visitor-Id":g.x("VISITOR_DATA")},method:"POST",body:g.Sc(c)},f=(0,g.r)(a.D,a);qd.then(function(){f();g.q("gapi.client.request")(e).execute(d||g.ea)})};
g.sd=function(a,b,c){this.A=a;this.B=b;this.C=c};
g.td=function(a){var b={};void 0!==a.A?b.trackingParams=a.A:(b.veType=a.B,null!=a.C&&(b.veCounter=a.C));return b};
g.yd=function(a,b){g.ud[a.endpoint]=g.ud[a.endpoint]||[];var c=g.ud[a.endpoint];c.push(a.Ab);vd[a.endpoint]=b;20<=c.length?g.wd():g.xd()};
g.wd=function(){g.xb(g.zd);if(!g.Ra(g.ud)){for(var a in g.ud){var b=g.Ad[a];if(!b){b=vd[a];if(!b)continue;b=new b;g.Ad[a]=b}var c=b.C();c.requestTimeMs=Math.round((0,g.Bd)());c[Daa[a]]=g.ud[a];b.B(a,c,{});delete g.ud[a]}g.Ra(g.ud)||g.xd()}};
g.xd=function(){g.xb(g.zd);g.zd=g.vb(g.wd,g.x("LOGGING_BATCH_TIMEOUT",1E4))};
g.Cd=function(a,b,c,d){var e={};e.eventTimeMs=Math.round(d||(0,g.Bd)());e[a]=b;g.yd({endpoint:"log_event",Ab:e},c)};
g.Dd=function(){};
g.Fd=function(a){if(a instanceof g.Dd)return a;if("function"==typeof a.fc)return a.fc(!1);if(g.ia(a)){var b=0,c=new g.Dd;c.next=function(){for(;;){if(b>=a.length)throw g.Ed;if(b in a)return a[b++];b++}};
return c}throw Error("Not implemented");};
g.Gd=function(a,b,c){if(g.ia(a))try{(0,g.z)(a,b,c)}catch(d){if(d!==g.Ed)throw d;}else{a=g.Fd(a);try{for(;;)b.call(c,a.next(),void 0,a)}catch(d){if(d!==g.Ed)throw d;}}};
g.Hd=function(a){if(g.ia(a))return g.La(a);a=g.Fd(a);var b=[];g.Gd(a,function(a){b.push(a)});
return b};
Eaa=function(){};
g.Id=function(){};
g.Jd=function(a){this.A=a};
g.Kd=function(){var a=null;try{a=window.localStorage||null}catch(b){}this.A=a};
Ld=function(){var a=null;try{a=window.sessionStorage||null}catch(b){}this.A=a};
g.Md=function(a){this.A=a};
Nd=function(a){this.A=a};
Od=function(a){this.data=a};
Pd=function(a){return!g.da(a)||a instanceof Od?a:new Od(a)};
g.Qd=function(a){this.A=a};
g.Rd=function(a){var b=a.creation;a=a.expiration;return!!a&&a<(0,g.F)()||!!b&&b>(0,g.F)()};
g.Sd=function(a){this.A=a};
g.Vd=function(a){if(!g.Td&&!g.Ud||!window.JSON)return null;var b;try{b=g.Td.get(a)}catch(c){}if(!g.ja(b))try{b=g.Ud.get(a)}catch(c){}if(!g.ja(b))return null;try{b=JSON.parse(b,void 0)}catch(c){}return b};
g.Wd=function(a){this.type="";this.state=this.source=this.data=this.currentTarget=this.relatedTarget=this.target=null;this.charCode=this.keyCode=0;this.shiftKey=this.ctrlKey=this.altKey=!1;this.rotation=this.clientY=this.clientX=0;this.scale=1;this.changedTouches=this.touches=null;if(a=a||window.event){this.event=a;for(var b in a)b in Faa||(this[b]=a[b]);this.scale=a.scale;this.rotation=a.rotation;(b=a.target||a.srcElement)&&3==b.nodeType&&(b=b.parentNode);this.target=b;if(b=a.relatedTarget)try{b=
b.nodeName?b:null}catch(c){b=null}else"mouseover"==this.type?b=a.fromElement:"mouseout"==this.type&&(b=a.toElement);this.relatedTarget=b;this.clientX=void 0!=a.clientX?a.clientX:a.pageX;this.clientY=void 0!=a.clientY?a.clientY:a.pageY;this.keyCode=a.keyCode?a.keyCode:a.which;this.charCode=a.charCode||("keypress"==this.type?this.keyCode:0);this.altKey=a.altKey;this.ctrlKey=a.ctrlKey;this.shiftKey=a.shiftKey;this.mn=a.pageX;this.nn=a.pageY}};
g.Yd=function(a,b,c,d){a.addEventListener&&("mouseenter"!=b||"onmouseenter"in window.document?"mouseleave"!=b||"onmouseenter"in window.document?"mousewheel"==b&&"MozBoxSizing"in window.document.documentElement.style&&(b="MozMousePixelScroll"):b="mouseout":b="mouseover");return g.Qa(g.Xd,function(e){return e[0]==a&&e[1]==b&&e[2]==c&&e[4]==!!d})};
g.G=function(a,b,c,d){if(!a||!a.addEventListener&&!a.attachEvent)return"";d=!!d;var e=g.Yd(a,b,c,d);if(e)return e;var e=++Zd.count+"",f=!("mouseenter"!=b&&"mouseleave"!=b||!a.addEventListener||"onmouseenter"in window.document),k;k=f?function(d){d=new g.Wd(d);if(!g.Jc(d.relatedTarget,function(b){return b==a},!0))return d.currentTarget=a,d.type=b,c.call(a,d)}:function(b){b=new g.Wd(b);
b.currentTarget=a;return c.call(a,b)};
k=g.ub(k);a.addEventListener?("mouseenter"==b&&f?b="mouseover":"mouseleave"==b&&f?b="mouseout":"mousewheel"==b&&"MozBoxSizing"in window.document.documentElement.style&&(b="MozMousePixelScroll"),a.addEventListener(b,k,d)):a.attachEvent("on"+b,k);g.Xd[e]=[a,b,c,k,d];return e};
g.$d=function(a){a&&("string"==typeof a&&(a=[a]),(0,g.z)(a,function(a){if(a in g.Xd){var c=g.Xd[a],d=c[0],e=c[1],f=c[3],c=c[4];d.removeEventListener?d.removeEventListener(e,f,c):d.detachEvent&&d.detachEvent("on"+e,f);delete g.Xd[a]}}))};
g.ae=function(a){a=a||window.event;a.returnValue=!1;a.preventDefault&&a.preventDefault()};
g.ce=function(){if(null==g.q("_lact",window)){var a=(0,window.parseInt)(g.x("LACT"),10),a=(0,window.isFinite)(a)?(0,g.F)()-Math.max(a,0):-1;g.n("_lact",a,window);-1==a&&be();g.G(window.document,"keydown",be);g.G(window.document,"keyup",be);g.G(window.document,"mousedown",be);g.G(window.document,"mouseup",be);g.y("page-mouse",be);g.y("page-scroll",be);g.y("page-resize",be)}};
be=function(){null==g.q("_lact",window)&&(g.ce(),g.q("_lact",window));var a=(0,g.F)();g.n("_lact",a,window);g.A("USER_ACTIVE")};
g.de=function(){var a=g.q("_lact",window);return null==a?-1:Math.max((0,g.F)()-a,0)};
g.ee=function(){return g.Vd("yt-interaction-logging-parent")};
g.fe=function(){var a=g.x("client-screen-nonce",void 0);a||(a=g.x("EVENT_ID",void 0));return a};
g.ge=function(a,b,c,d,e,f,k){var l="";a&&(l+=a+":");c&&(l+="//",b&&(l+=b+"@"),l+=c,d&&(l+=":"+d));e&&(l+=e);f&&(l+="?"+f);k&&(l+="#"+k);return l};
g.he=function(a){return a?(0,window.decodeURI)(a):a};
g.je=function(a,b){return b.match(g.ie)[a]||null};
g.ke=function(a){return g.he(g.je(3,a))};
g.le=function(a){a=a.match(g.ie);return g.ge(null,null,null,null,a[5],a[6],a[7])};
g.me=function(a){var b=a.indexOf("#");return 0>b?a:a.substr(0,b)};
g.ne=function(a){if(a[1]){var b=a[0],c=b.indexOf("#");0<=c&&(a.push(b.substr(c)),a[0]=b=b.substr(0,c));c=b.indexOf("?");0>c?a[1]="?":c==b.length-1&&(a[1]=void 0)}return a.join("")};
g.oe=function(a,b,c){if(g.ha(b))for(var d=0;d<b.length;d++)g.oe(a,String(b[d]),c);else null!=b&&c.push("&",a,""===b?"":"=",g.wa(b))};
pe=function(a,b){for(var c in b)g.oe(c,b[c],a);return a};
g.qe=function(a){a=pe([],a);a[0]="";return a.join("")};
g.re=function(a,b){return g.ne(pe([a],b))};
g.se=function(a,b,c){a&&(c&&(c=g.Xa,c=!(c&&0<=c.toLowerCase().indexOf("cobalt"))),c?a&&(a=g.Dc("IFRAME",{src:'javascript:"data:text/html,<body><img src=\\"'+a+'\\"></body>"',style:"display:none"}),g.Ic(a).body.appendChild(a)):Gaa(a,b))};
g.te=function(a){try{window.navigator&&window.navigator.sendBeacon&&window.navigator.sendBeacon(a,"")||g.se(a,void 0)}catch(b){g.se(a,void 0)}};
Gaa=function(a,b){var c=new window.Image,d=""+Haa++;ue[d]=c;c.onload=c.onerror=function(){b&&ue[d]&&b();delete ue[d]};
c.src=a};
g.ve=function(a,b){this.version=a;this.args=b};
g.we=function(a,b){this.topic=a;this.xf=b};
g.ye=function(a,b){var c=g.xe();return c?c.publish.call(c,a.toString(),a,b):!1};
g.xe=function(){return g.q("yt.pubsub2.instance_")};
ze=function(a){g.ve.call(this,1,arguments)};
g.Ae=function(a,b,c,d){this.top=a;this.right=b;this.bottom=c;this.left=d};
g.Be=function(a,b){return a&&b?b instanceof g.Ae?b.left>=a.left&&b.right<=a.right&&b.top>=a.top&&b.bottom<=a.bottom:b.x>=a.left&&b.x<=a.right&&b.y>=a.top&&b.y<=a.bottom:!1};
g.Ce=function(a,b,c,d){this.left=a;this.top=b;this.width=c;this.height=d};
g.De=function(a,b){var c=Math.max(a.left,b.left),d=Math.min(a.left+a.width,b.left+b.width);if(c<=d){var e=Math.max(a.top,b.top),f=Math.min(a.top+a.height,b.top+b.height);if(e<=f)return a.left=c,a.top=e,a.width=d-c,a.height=f-e,!0}return!1};
g.Ee=function(a){return new g.mc(a.width,a.height)};
Ge=function(a){this.A=a||window;this.R=this.B=0;if(this.A.performance&&this.A.performance.timing&&this.A.performance.getEntriesByType){a=g.xc(this.A);this.G=new g.Ce(0,0,a.width,a.height);a=[];for(var b=this.A.document.getElementsByTagName("*"),c=0,d=b.length;c<d;c++){var e=b[c];if("IMG"==e.tagName||"IFRAME"==e.tagName){var f=Fe(this,e,e.src);if(f){if("IFRAME"==e.tagName){var k;try{k=(new Ge(e.contentWindow)).B}catch(l){k=0}0<k&&(f.timing=k)}a.push(f)}}(f=this.A.getComputedStyle(e)["background-image"])&&
(f=Ge.A.exec(f))&&1<f.length&&(f=Fe(this,e,f[1]))&&a.push(f)}this.C=a;this.F=this.A.performance.getEntriesByType("resource");this.K=this.A.performance.getEntriesByType("mark");k={};a=0;for(b=this.F.length;a<b;a++)c=this.F[a],k[c.name]=c.responseEnd;a=0;for(b=this.K.length;a<b;a++)c=this.K[a],"mark_iframe_loaded: "==c.name.slice(0,20)&&(k[c.name.slice(20)]=c.startTime);a=0;for(b=this.C.length;a<b;a++)c=this.C[a],c.timing||(c.timing=k[c.url]||0);this.H=Iaa(this);this.D=Jaa(this);e=k=0;if(this.D.length)for(b=
a=0,c=this.D.length;b<c;b++)d=this.D[b],e=d.timing-e,0<e&&1>a&&(k+=(1-a)*e),e=d.timing,a=d.progress;this.B=Math.round(k||this.H);this.R=e}};
Fe=function(a,b,c){return c&&b.getBoundingClientRect&&(b=b.getBoundingClientRect(),b=new g.Ce(b.left,b.top,b.width,b.height),g.De(b,a.G))?new He(b,c):null};
Iaa=function(a){var b,c=a.A,d=c.performance.timing.navigationStart;if("msFirstPaint"in c.performance.timing)b=c.performance.timing.A-d;else if("chrome"in c&&"loadTimes"in c.chrome){var e=c.chrome.loadTimes(),f=e.firstPaintTime;if(0<f){var k=e.startLoadTime;"requestTime"in e&&(k=e.requestTime);f>=k&&(b=1E3*(f-k))}}if(void 0===b||0>b||12E4<b){b=c.performance.timing.responseStart-d;for(var l={},c=c.document.getElementsByTagName("head")[0].children,d=0,e=c.length;d<e;d++)f=c[d],"SCRIPT"==f.tagName&&f.src&&
!f.async?l[f.src]=!0:"LINK"==f.tagName&&"stylesheet"==f.rel&&f.href&&(l[f.href]=!0);a.F.some(function(a){if(!l[a.name]||"script"!=a.initiatorType&&"link"!=a.initiatorType)return!0;a=a.responseEnd;if(void 0===b||a>b)b=a})}return Math.max(b,0)||0};
Jaa=function(a){for(var b={0:0},c=0,d=a.H,e=0,f=a.C.length;e<f;e++){var k=a.C[e],l=d;k.timing>d&&(l=k.timing);b[l]||(b[l]=0);k=g.Ee(k.region).og();b[l]+=k;c+=k}e=g.Ee(a.G).og();0<e&&(e=.1*Math.max(e-c,0),d in b||(b[d]=0),b[d]+=e,c+=e);d=[];if(c){for(var p in b)a=new Ie((0,window.parseFloat)(p),b[p]),d.push(a);d.sort(function(a,b){return a.timing-b.timing});
e=b=0;for(f=d.length;e<f;e++)a=d[e],b+=a.og,a.progress=b/c}return d};
He=function(a,b){this.region=a;this.url=b};
Ie=function(a,b){this.og=b;this.timing=a};
Ke=function(a){Je.mark&&(Kaa.test(a)||(a="mark_"+a),Je.mark(a))};
Laa=function(){if("cold"==Le().yt_lt){var a=Me(),b=Ne(),c;for(c in a)g.ua(c,"_")||"tick_"+c in b||Oe(c,a[c]);a=Le();for(c in a)"info_"+c in b||Pe(c,a[c])}};
g.Re=function(a,b,c){b||"_"==a[0]||Ke(a);var d=Me(c),e=b||(0,g.Bd)();d[a]&&(d["_"+a]=d["_"+a]||[d[a]],d["_"+a].push(e));d[a]=e;Oe(a,b,c)||g.Qe(!1,c);return d[a]};
Oe=function(a,b,c){Ne(c)["tick_"+a]=b;return g.Oc("csi_on_gel")?(c=Se(c),"_start"==a?g.Cd("latencyActionBaselined",{clientActionNonce:c},rd,b):g.Cd("latencyActionTicked",{tickName:a,clientActionNonce:c},rd,b),!0):!1};
Ue=function(a,b){Te("yt_sts",a,void 0);g.Re("_start",b,void 0)};
Te=function(a,b,c){Le(c)[a]=b;Pe(a,b,c)};
Pe=function(a,b,c){Ne(c)["info_"+a]=b;if(g.Oc("csi_on_gel"))if(a in Ve){var d={};a=Ve[a];g.Ia(Maa,a)&&(b=!!b);d[a]=b;b=Se(c);d.clientActionNonce=b;g.Cd("latencyActionInfo",d,rd)}else g.zb(Error("Unknown label "+a+" logged with GEL CSI."))};
Ye=function(a){We(a);Naa();Xe(!1,a)};
Qaa=function(){var a=g.x("TIMING_INFO",{}),b;for(b in a)Te(b,a[b]);(a=g.fe())&&Te("csn",a);(a=g.x("PREVIOUS_ACTION",void 0))&&Te("pa",a);a=Le();a.p=g.x("CLIENT_PROTOCOL")||"unknown";a.t=g.x("CLIENT_TRANSPORT")||"unknown";Je.now&&Je.timing?(a=Je.timing.navigationStart+Je.now(),a=Math.round((0,g.F)()-a)):a=null;null!=a&&Te("yt_hrd",a);window.navigator&&window.navigator.sendBeacon&&Te("ba",1);Te("yt_vis",Oaa());if("cold"==Le().yt_lt){a=Je.timing||{};g.Oc("cold_load_nav_start_web")&&a.navigationStart&&
(Ue("n",a.navigationStart),g.Re("srt",a.responseStart));a:if(a.msFirstPaint)b=Math.max(0,a.msFirstPaint);else{if(b=window.chrome)if(b=b.loadTimes,g.ma(b)){b=b();var c=1E3*Math.min(b.requestTime||window.Infinity,b.startLoadTime||window.Infinity),c=window.Infinity===c?0:a.navigationStart-c;b=Math.max(0,Math.round(1E3*b.firstPaintTime+c)||0);break a}b=0}0<b&&g.Re("fpt",b);Ze(a);Je.getEntriesByType&&Paa();a=g.x("SPEEDINDEX_FOR_ACTIONS",void 0);b=g.x("TIMING_ACTION",void 0);a&&-1<a.indexOf(b)&&(a=(0,g.Bd)(),
b=new Ge,c=(0,g.Bd)(),0<b.B&&(Te("si",b.B),g.Re("vsc",$e(b.R)),g.Re("sics",a),g.Re("sice",c)));a=[];if(window.document.querySelector&&Je&&Je.getEntriesByName)for(var d in af)if(b=window.document.querySelector(d)){var c="",e=b.nodeName;"SCRIPT"==e?c=b.src:"LINK"==e&&(c=b.href);c&&(b=Je.getEntriesByName(c))&&b[0]&&a.push(af[d]+"."+Math.round(b[0].duration))}a.length&&Te("rs",a.join(","))}};
bf=function(a){var b=Me(a);if(b.aft)return b.aft;a=g.x((a||"")+"TIMING_AFT_KEYS",["ol"]);for(var c=a.length,d=0;d<c;d++){var e=b[a[d]];if(e)return e}return window.NaN};
Ze=function(a){g.Re("nreqs",a.requestStart,void 0);g.Re("nress",a.responseStart,void 0);g.Re("nrese",a.responseEnd,void 0);0<a.redirectEnd-a.redirectStart&&(g.Re("nrs",a.redirectStart,void 0),g.Re("nre",a.redirectEnd,void 0));0<a.domainLookupEnd-a.domainLookupStart&&(g.Re("ndnss",a.domainLookupStart,void 0),g.Re("ndnse",a.domainLookupEnd,void 0));0<a.connectEnd-a.connectStart&&(g.Re("ntcps",a.connectStart,void 0),g.Re("ntcpe",a.connectEnd,void 0));a.secureConnectionStart>=a.navigationStart&&0<a.connectEnd-
a.secureConnectionStart&&(g.Re("nstcps",a.secureConnectionStart,void 0),g.Re("ntcpe",a.connectEnd,void 0))};
$e=function(a){return Math.round(Je.timing.navigationStart+a)};
Paa=function(){var a=window.location.protocol,b=Je.getEntriesByType("resource"),c=b.filter(function(b){return 0==b.name.indexOf(a+"//fonts.googleapis.com/css?family=")})[0],b=b.filter(function(b){return 0==b.name.indexOf(a+"//fonts.gstatic.com/s/")}).reduce(function(a,b){return b.duration>a.duration?b:a},{duration:0});
c&&0<c.startTime&&0<c.responseEnd&&(g.Re("wfcs",$e(c.startTime)),g.Re("wfce",$e(c.responseEnd)));b&&0<b.startTime&&0<b.responseEnd&&(g.Re("wffs",$e(b.startTime)),g.Re("wffe",$e(b.responseEnd)))};
ef=function(a){var b=Me(a),c=Le(a),d=b._start,e;for(e in b)if(g.ua(e,"_")&&g.ha(b[e])){var f=e.slice(1);if(f in Raa){var k=(0,g.cf)(b[e],function(a){return Math.round(a-d)});
c["all_"+f]=k.join()}delete b[e]}f=!!c.ap;if(k=g.q("yt.timing.reportbuilder_")){if(k=k(b,c,a))df(k,f),Ye(a)}else{var l=g.x("CSI_SERVICE_NAME","youtube"),k={v:2,s:l,action:g.x((a||"")+"TIMING_ACTION",void 0)},p=c.srt;delete c.srt;void 0===b.srt&&(p||0===p||(p=Je.timing||{},p=Math.max(0,p.responseStart-p.navigationStart),(0,window.isNaN)(p)&&c.pt&&(p=c.pt)),p||0===p)&&(c.srt=Math.round(p));if(c.h5jse){var u=window.location.protocol+g.q("ytplayer.config.assets.js");(u=Je.getEntriesByName?Je.getEntriesByName(u)[0]:
null)?c.h5jse=Math.round(c.h5jse-u.responseEnd):delete c.h5jse}b.aft=bf(a);Saa(a)&&"youtube"==l&&(Te("yt_lt","hot_bg",a),l=b.vc,u=b.pbs,delete b.aft,c.aft=Math.round(u-l));for(var w in c)"_"!=w.charAt(0)&&(k[w]=c[w]);b.ps=(0,g.Bd)();c={};w=[];for(e in b)"_"!=e.charAt(0)&&(l=Math.round(b[e]-d),c[e]=l,w.push(e+"."+l));k.rt=w.join(",");(b=g.q("ytdebug.logTiming"))&&b(k,c);g.Oc("navigation_only_csi_reset")||Ye(a);df(k,f,a);g.ye(Taa,new ze(c.aft+(p||0)))}};
g.Qe=function(a,b){if(!ff(b)||!g.Oc("navigation_only_csi_reset")&&!b){var c=g.x((b||"")+"TIMING_ACTION",void 0),d=Me(b);if(g.q("yt.timing."+(b||"")+"ready_")&&c&&d._start&&bf(b))if(a||b)ef(b);else{var c=!0,e=g.x("TIMING_WAIT",[]);if(e.length)for(var f=0,k=e.length;f<k;++f)if(!(e[f]in d)){c=!1;break}c&&ef(b)}}};
df=function(a,b,c){if(g.Oc("debug_csi_data")){var d=g.q("yt.timing.csiData");d||(d=[],g.n("yt.timing.csiData",d,void 0));d.push({page:window.location.href,time:new Date,args:a})}var d="",e;for(e in a)d+="&"+e+"="+a[e];a="/csi_204?"+d.substring(1);window.navigator&&window.navigator.sendBeacon&&b?g.te(a):g.se(a);Xe(!0,c)};
gf=function(a){g.n("yt.timing.ready_",a,void 0)};
Se=function(a){var b=hf(a).nonce;if(!b){var c;a:{if(window.crypto&&window.crypto.getRandomValues)try{var d=Array(16),e=new window.Uint8Array(16);window.crypto.getRandomValues(e);for(b=0;b<d.length;b++)d[b]=e[b];c=d;break a}catch(f){}c=Array(16);for(d=0;16>d;d++){e=(0,g.F)();for(b=0;b<e%23;b++)c[d]=Math.random();c[d]=Math.floor(256*Math.random())}if(jf)for(d=1,e=0;e<jf.length;e++)c[d%16]=c[d%16]^c[(d-1)%16]/4^jf.charCodeAt(e),d++}d=[];for(e=0;e<c.length;e++)d.push("abcdefghijklmnopqrstuvwxyzABCDEFGHIJKLMNOPQRSTUVWXYZ0123456789-_".charAt(c[e]&
63));b=d.join("");hf(a).nonce=b}return b};
Me=function(a){return hf(a).tick};
Le=function(a){return hf(a).info};
Ne=function(a){a=hf(a);"gel"in a||(a.gel={});return a.gel};
hf=function(a){return g.q("ytcsi."+(a||"")+"data_")||We(a)};
We=function(a){var b={tick:{},info:{}};g.n("ytcsi."+(a||"")+"data_",b,void 0);return b};
ff=function(a){return!!g.q("yt.timing."+(a||"")+"pingSent_")};
Xe=function(a,b){g.n("yt.timing."+(b||"")+"pingSent_",a,void 0)};
kf=function(a){if(!ff(void 0)){if(!g.Oc("send_empty_timing")){var b=g.x("CSI_SERVICE_NAME","youtube");if(!g.x("TIMING_ACTION",void 0)||!b)return}g.Re("aa",void 0,void 0);Te("ap",1,void 0);Te("yt_fss",a,void 0);ef(void 0)}};
Saa=function(a){var b=Me(a),c=b.pbr,d=b.vc,b=b.pbs;return c&&d&&b&&c<d&&d<b&&1==Le(a).yt_pvis};
Oaa=function(){switch(g.Nc()){case "hidden":return 0;case "visible":return 1;case "prerender":return 2;case "unloaded":return 3}return-1};
g.lf=function(a){this.A=a||{cookie:""}};
g.nf=function(a){a=(a.A.cookie||"").split(g.mf);for(var b=[],c=[],d,e,f=0;e=a[f];f++)d=e.indexOf("="),-1==d?(b.push(""),c.push(e)):(b.push(e.substring(0,d)),c.push(e.substring(d+1)));return{keys:b,values:c}};
g.pf=function(a,b,c,d){g.of.set(""+a,b,c,"/",d||"youtube.com")};
g.sf=function(a,b,c){var d=g.x("VALID_SESSION_TEMPDATA_DOMAINS",[]),e=g.ke(window.location.href);e&&d.push(e);e=g.ke(a);if(g.Ia(d,e)||!e&&g.ua(a,"/"))if(a=g.le(a),a=g.me(a))c?(c=(0,window.parseInt)(c,10),(0,window.isFinite)(c)&&0<c&&(qf(a,b,c),rf(b))):(qf(a,b),rf(b))};
qf=function(a,b,c){a="ST-"+g.Da(a).toString(36);c=c||5;b=b?g.qe(b):"";g.pf(a,b,c)};
rf=function(a){if(a){a=a.itct||a.ved;var b=g.q("yt.logging.screenreporter.storeParentElement");a&&b&&b(new g.sd(a))}};
g.tf=function(a,b){g.se("/gen_204?"+a,b)};
uf=function(a){a=a||{};this.url=a.url||"";this.urlV9As2=a.url_v9as2||"";this.args=a.args||g.Ua(Uaa);this.assets=a.assets||{};this.attrs=a.attrs||g.Ua(Vaa);this.params=a.params||g.Ua(Waa);this.minVersion=a.min_version||"8.0.0";this.fallback=a.fallback||null;this.fallbackMessage=a.fallbackMessage||null;this.html5=!!a.html5;this.disable=a.disable||{};this.loaded=!!a.loaded;this.messages=a.messages||{}};
g.vf=function(a){a instanceof uf||(a=new uf(a));return a};
xf=function(){return null!=g.wf};
g.yf=function(){return g.wf?g.wf.invoke():null};
zf=function(){return(0,window.parseInt)(g.x("DCLKSTAT",0),10)};
g.Af=function(a,b,c){c=c||"";g.fc(window.location,g.re(a,b||{})+c)};
g.Bf=function(a,b){b&&g.sf(a,b);(window.ytspf||{}).enabled?window.spf.navigate(a):g.Af(a)};
g.Cf=function(a,b,c){var d=g.x("EVENT_ID");d&&(b||(b={}),b.ei||(b.ei=d));b&&g.sf(a,b);if(c)return!1;g.Bf(a);return!0};
g.Df=function(a,b){"number"==typeof a&&(a=(b?Math.round(a):a)+"px");return a};
g.Ef=function(a,b){a.style.height=g.Df(b,!0)};
g.Ff=function(a,b){a.style.width=g.Df(b,!0)};
g.Hf=function(){this.A=this.minor=this.major=0;this.C="";var a=g.q("window.navigator.plugins"),b=g.q("window.navigator.mimeTypes"),a=a&&a["Shockwave Flash"],b=b&&b["application/x-shockwave-flash"],b=a&&b&&b.enabledPlugin&&a.description||"";if(a=b){var c=a.indexOf("Shockwave Flash");0<=c&&(a=a.substr(c+15));for(var c=a.split(" "),d="",a="",e=0,f=c.length;e<f;e++)if(d)if(a)break;else a=c[e];else d=c[e];d=d.split(".");c=(0,window.parseInt)(d[0],10)||0;d=(0,window.parseInt)(d[1],10)||0;e=0;if("r"==a.charAt(0)||
"d"==a.charAt(0))e=(0,window.parseInt)(a.substr(1),10)||0;a=[c,d,e]}else a=[0,0,0];this.C=b;b=a;this.major=b[0];this.minor=b[1];this.A=b[2];if(0>=this.major){var k,l,p,u;if(g.Gf)try{k=new window.ActiveXObject("ShockwaveFlash.ShockwaveFlash")}catch(w){k=null}else p=window.document.body,u=window.document.createElement("object"),u.setAttribute("type","application/x-shockwave-flash"),k=p.appendChild(u);if(k&&"GetVariable"in k)try{l=k.GetVariable("$version")}catch(w){l=""}p&&u&&p.removeChild(u);(k=l||
"")?(k=k.split(" ")[1].split(","),k=[(0,window.parseInt)(k[0],10)||0,(0,window.parseInt)(k[1],10)||0,(0,window.parseInt)(k[2],10)||0]):k=[0,0,0];this.major=k[0];this.minor=k[1];this.A=k[2]}};
g.If=function(a,b,c,d){b="string"==typeof b?b.split("."):[b,c,d];b[0]=(0,window.parseInt)(b[0],10)||0;b[1]=(0,window.parseInt)(b[1],10)||0;b[2]=(0,window.parseInt)(b[2],10)||0;return a.major>b[0]||a.major==b[0]&&a.minor>b[1]||a.major==b[0]&&a.minor==b[1]&&a.A>=b[2]};
g.Jf=function(a){return-1<a.C.indexOf("Gnash")&&-1==a.C.indexOf("AVM2")||9==a.major&&1==a.minor||9==a.major&&0==a.minor&&1==a.A?!1:9<=a.major};
g.Kf=function(a){return-1<window.navigator.userAgent.indexOf("Sony/COM2")&&!g.If(a,9,1,58)?!1:!0};
g.Lf=function(a,b,c){if(b){a=g.ja(a)?g.tc(a):a;var d=g.Ua(c.attrs);d.tabindex=0;var e=g.Ua(c.params);e.flashvars=g.qe(c.args);if(g.Gf){d.classid="clsid:D27CDB6E-AE6D-11cf-96B8-444553540000";e.movie=b;b=window.document.createElement("object");for(var f in d)b.setAttribute(f,d[f]);for(f in e)d=window.document.createElement("param"),d.setAttribute("name",f),d.setAttribute("value",e[f]),b.appendChild(d)}else{d.type="application/x-shockwave-flash";d.src=b;b=window.document.createElement("embed");b.setAttribute("name",
d.id);for(f in d)b.setAttribute(f,d[f]);for(f in e)b.setAttribute(f,e[f])}e=window.document.createElement("div");e.appendChild(b);a.innerHTML=e.innerHTML}};
g.Mf=function(a,b){var c=a.match(Xaa);window.spf.style.load(a,c?c[1]:"",b)};
Nf=function(a){g.mb.call(this);this.A=[];this.C=a||this};
Of=function(a,b,c,d){d=g.ub((0,g.r)(d,a.C));b.addEventListener(c,d);a.A.push({target:b,name:c,Kb:d})};
Pf=function(a){for(;a.A.length;){var b=a.A.pop();b.target.removeEventListener(b.name,b.Kb)}};
Sf=function(a,b){g.mb.call(this);this.K=this.D=a;this.ha=b;this.H=!1;this.api={};this.la=this.T=null;this.X=new g.qb;g.pb(this,this.X);this.B={};this.G=this.Ra=this.C=this.ib=this.A=null;this.aa=!1;this.R=this.F=this.M=this.P=null;this.Wa={};this.Hb=["onReady"];this.ea=new Nf(this);g.pb(this,this.ea);this.lb=null;this.wb=window.NaN;this.ga={};Qf(this);this.ie("onDetailedError",(0,g.r)(this.VI,this));this.ie("onTabOrderChange",(0,g.r)(this.jy,this));this.ie("onTabAnnounce",(0,g.r)(this.ep,this));this.ie("WATCH_LATER_VIDEO_ADDED",
(0,g.r)(this.YI,this));this.ie("WATCH_LATER_VIDEO_REMOVED",(0,g.r)(this.ZI,this));g.Rf||(this.ie("onMouseWheelCapture",(0,g.r)(this.CI,this)),this.ie("onMouseWheelRelease",(0,g.r)(this.DI,this)));this.ie("onAdAnnounce",(0,g.r)(this.ep,this));this.Y=new Nf(this);g.pb(this,this.Y);this.bb=!1;this.ab=null};
Uf=function(a,b){a.ib=b;a.A=b.clone();a.C=a.A.attrs.id||a.C;"video-player"==a.C&&(a.C=a.ha,a.A.attrs.id=a.ha);a.K.id==a.C&&(a.C+="-player",a.A.attrs.id=a.C);a.A.args.enablejsapi="1";a.A.args.playerapiid=a.ha;a.Ra||(a.Ra=Tf(a,a.A.args.jsapicallback||"onYouTubePlayerReady"));a.A.args.jsapicallback=null;var c=a.A.attrs.width;c&&g.Ff(a.K,Number(c)||c);(c=a.A.attrs.height)&&g.Ef(a.K,Number(c)||c)};
Vf=function(a){a.A.loaded||(a.A.loaded=!0,"0"!=a.A.args.autoplay?a.api.loadVideoByPlayerVars(a.A.args):a.api.cueVideoByPlayerVars(a.A.args))};
Wf=function(a){if(!g.da(a.A.disable.flash)){var b=a.A.disable,c;c=g.If(g.Hf.getInstance(),a.A.minVersion);b.flash=!c}return!a.A.disable.flash};
Zf=function(a,b){if((!b||(5!=(Yaa[b.errorCode]||5)?0:-1!=Zaa.indexOf(b.errorCode)))&&Wf(a)){var c=Xf(a);c&&c.stopVideo&&c.stopVideo();var d=a.A;c&&c.getUpdatedConfigurationData&&(c=c.getUpdatedConfigurationData(),d=g.vf(c));d.args.autoplay=1;d.args.html5_unavailable="1";Uf(a,d);Yf(a,"flash")}};
Yf=function(a,b){if(!a.fb()){if(!b){var c;if(!(c=!a.A.html5&&Wf(a))){if(!g.da(a.A.disable.html5)){var d;c=!0;void 0!=a.A.args.deviceHasDisplay&&(c=a.A.args.deviceHasDisplay);if(2.2==$f)d=!0;else{a:{var e=c;c=g.q("yt.player.utils.videoElement_");c||(c=window.document.createElement("video"),g.n("yt.player.utils.videoElement_",c,void 0));try{if(c.canPlayType)for(var e=e?$aa:aba,f=0;f<e.length;f++)if(c.canPlayType(e[f])){d=null;break a}d="fmt.noneavailable"}catch(k){d="html5.missingapi"}}d=!d}d&&(d=ag(a)||
a.A.assets.js);a.A.disable.html5=!d;d||(a.A.args.html5_unavailable="1")}c=!!a.A.disable.html5}b=c?Wf(a)?"flash":"unsupported":"html5"}("flash"==b?a.cP:a.dP).call(a)}};
ag=function(a){var b=!0,c=Xf(a);c&&a.A&&(a=a.A,b=g.B(c,"version")==a.assets.js);return b&&!!g.q("yt.player.Application.create")};
Xf=function(a){var b=g.D(a.C);!b&&a.K&&a.K.querySelector&&(b=a.K.querySelector("#"+a.C));return b};
bg=function(a,b,c){var d=b[c];return function(){try{return a.lb=null,d.apply(b,arguments)}catch(e){"Bad NPObject as private data!"!=e.message&&"sendAbandonmentPing"!=c&&(e.message+=" ("+c+")",a.lb=e,g.zb(e,"WARNING"))}}};
Qf=function(a){a.H=!1;if(a.la)for(var b in a.B)a.la(b,a.B[b]);for(var c in a.ga)g.xb((0,window.parseInt)(c,10));a.ga={};a.T=null;a.la=null;for(var d in a.api)a.api[d]=null;a.api.addEventListener=(0,g.r)(a.ie,a);a.api.removeEventListener=(0,g.r)(a.jN,a);a.api.destroy=(0,g.r)(a.dispose,a);a.api.getLastError=(0,g.r)(a.Lz,a);a.api.getPlayerType=(0,g.r)(a.aA,a);a.api.getCurrentVideoConfig=(0,g.r)(a.hz,a);a.api.loadNewVideoConfig=(0,g.r)(a.zo,a);a.api.isReady=(0,g.r)(a.rP,a)};
Tf=function(a,b){var c=b;if("string"==typeof b){if(a.Wa[b])return a.Wa[b];c=function(){var a=g.q(b);a&&a.apply(g.m,arguments)};
a.Wa[b]=c}return c?c:null};
bba=function(a,b){var c="ytPlayer"+b+a.ha;a.B[b]=c;g.m[c]=function(c){var e=g.vb(function(){a.fb()||(a.X.Ea(b,c),g.Sa(a.ga,String(e)))},0);
g.Ta(a.ga,String(e),!0)};
return c};
cg=function(a){return(a=Xf(a))?"div"==a.tagName.toLowerCase()?"html5":"flash":null};
dg=function(a){g.Re("dcp");a.cancel();Qf(a);a.G=null;a.A&&(a.A.loaded=!1);var b=Xf(a);"html5"==cg(a)?a.M=b:b&&b.destroy&&b.destroy();g.Fc(a.D);Pf(a.ea);a.F=null;a.R=null};
g.gg=function(a,b){a=g.ja(a)?g.tc(a):a;b=g.vf(b);var c=g.eg+"_"+g.pa(a),d=g.fg[c];if(d)return d.zo(b),d.api;d=new Sf(a,c);g.fg[c]=d;g.A("player-added",d.api);g.nb(d,g.t(cba,d));g.vb(function(){d.zo(b)},0);
return d.api};
cba=function(a){g.fg[a.getId()]=null};
g.hg=function(a){a=g.D(a);if(!a)return null;var b=g.eg+"_"+g.pa(a),c=g.fg[b];c||(c=new Sf(a,b),g.fg[b]=c);return c.api};
g.ig=function(){return g.C(g.D("page-container"),"remote-connected")};
dba=function(){g.n("yt.abuse.botguardInitialized",xf,void 0);g.n("yt.abuse.invokeBotguard",g.yf,void 0);g.n("yt.abuse.dclkstatus.checkDclkStatus",zf,void 0);g.n("yt.player.exports.navigate",g.Cf,void 0);g.n("yt.player.embed",g.gg,void 0);g.n("yt.player.getPlayerByElement",g.hg,void 0);g.n("yt.util.activity.init",g.ce,void 0);g.n("yt.util.activity.getTimeSinceActive",g.de,void 0);g.n("yt.util.activity.setTimestamp",be,void 0);var a=g.q("ytplayer.config");jg(a);g.q("ytspf.enabled")&&(kg=g.wb(lg,5E3),
(a=g.mg())?(a.addEventListener("onReady",lg),a.addEventListener("onStateChange",lg)):ng("unable to init PP monitor"))};
jg=function(a){for(var b in g.fg){var c=g.fg[b];c&&c.cancel()}if(a=a||null){b=g.mg();var d=!0,c=g.og;g.og=null;b&&b.getVideoData&&c&&(d=b.getVideoData(),d=!!c.fullscreen||d.video_id!=a.args.video_id||d.list!=a.args.list||d.video_id!=c.videoId||d.list!=c.listId);d?(pg="",g.gg("player-api",a)):b.playVideo();a=g.vf(a);a.loaded=!0}lg();g.n("ytplayer.config",a,void 0)};
g.mg=function(){var a=g.q("yt.player.getPlayerByElement");return a?a("player-api"):null};
lg=function(){var a=g.mg();if(a){var b;b=g.D("player");b=!b||g.C(b,"off-screen");var c=1==(a&&a.isReady()?a.getPlayerState():void 0),d="watch"==g.x("PAGE_NAME"),e=g.ig();!c||d||e||(ng("PP playing off watch (paused)"),a.pauseVideo());b&&d?ng("PP off-screen on watch"):b||d||ng("PP !off-screen off watch")}};
ng=function(a){var b=g.x("PAGE_NAME");b&&(b=[b,pg,g.q("_spf_state.nav-counter")],a+="("+b.join(",")+")",g.n("yt.www.persistentplayer.issue",a,void 0),g.zb(Error(a),"WARNING"))};
g.qg=function(a,b){this.type=a;this.currentTarget=this.target=b;this.defaultPrevented=this.Zf=!1;this.hv=!0};
g.rg=function(a,b){g.qg.call(this,a?a.type:"");this.relatedTarget=this.currentTarget=this.target=null;this.charCode=this.keyCode=this.button=this.screenY=this.screenX=this.clientY=this.clientX=this.offsetY=this.offsetX=0;this.metaKey=this.shiftKey=this.altKey=this.ctrlKey=!1;this.state=null;this.rn=!1;this.tb=null;a&&this.init(a,b)};
g.tg=function(a){return!(!a||!a[sg])};
fba=function(a,b,c,d,e){this.listener=a;this.A=null;this.src=b;this.type=c;this.vh=!!d;this.od=e;this.key=++eba;this.Tg=this.Ni=!1};
ug=function(a){a.Tg=!0;a.listener=null;a.A=null;a.src=null;a.od=null};
vg=function(a){this.src=a;this.A={};this.C=0};
g.xg=function(a,b,c,d,e,f){var k=b.toString();b=a.A[k];b||(b=a.A[k]=[],a.C++);var l=wg(b,c,e,f);-1<l?(a=b[l],d||(a.Ni=!1)):(a=new fba(c,a.src,k,!!e,f),a.Ni=d,b.push(a));return a};
yg=function(a,b){var c=b.type;if(!(c in a.A))return!1;var d=g.Ka(a.A[c],b);d&&(ug(b),0==a.A[c].length&&(delete a.A[c],a.C--));return d};
g.zg=function(a,b,c,d,e){a=a.A[b.toString()];b=-1;a&&(b=wg(a,c,d,e));return-1<b?a[b]:null};
wg=function(a,b,c,d){for(var e=0;e<a.length;++e){var f=a[e];if(!f.Tg&&f.listener==b&&f.vh==!!c&&f.od==d)return e}return-1};
g.Ag=function(a,b,c,d,e){if(g.ha(b)){for(var f=0;f<b.length;f++)g.Ag(a,b[f],c,d,e);return null}c=g.Bg(c);return g.tg(a)?a.O(b,c,d,e):g.Cg(a,b,c,!1,d,e)};
g.Cg=function(a,b,c,d,e,f){if(!b)throw Error("Invalid event type");var k=!!e,l=g.Dg(a);l||(a[Eg]=l=new vg(a));c=g.xg(l,b,c,d,e,f);if(c.A)return c;d=gba();c.A=d;d.src=a;d.listener=c;if(a.addEventListener)a.addEventListener(b.toString(),d,k);else if(a.attachEvent)a.attachEvent(Fg(b.toString()),d);else throw Error("addEventListener and attachEvent are unavailable.");Gg++;return c};
gba=function(){var a=hba,b=Hg?function(c){return a.call(b.src,b.listener,c)}:function(c){c=a.call(b.src,b.listener,c);
if(!c)return c};
return b};
g.Ig=function(a,b,c,d,e){if(g.ha(b))for(var f=0;f<b.length;f++)g.Ig(a,b[f],c,d,e);else c=g.Bg(c),g.tg(a)?a.Va(b,c,d,e):a&&(a=g.Dg(a))&&(b=g.zg(a,b,c,!!d,e))&&g.Jg(b)};
g.Jg=function(a){if(g.ka(a)||!a||a.Tg)return!1;var b=a.src;if(g.tg(b))return yg(b.Y,a);var c=a.type,d=a.A;b.removeEventListener?b.removeEventListener(c,d,a.vh):b.detachEvent&&b.detachEvent(Fg(c),d);Gg--;(c=g.Dg(b))?(yg(c,a),0==c.C&&(c.src=null,b[Eg]=null)):ug(a);return!0};
Fg=function(a){return a in Kg?Kg[a]:Kg[a]="on"+a};
Mg=function(a,b,c,d){var e=!0;if(a=g.Dg(a))if(b=a.A[b.toString()])for(b=b.concat(),a=0;a<b.length;a++){var f=b[a];f&&f.vh==c&&!f.Tg&&(f=Lg(f,d),e=e&&!1!==f)}return e};
Lg=function(a,b){var c=a.listener,d=a.od||a.src;a.Ni&&g.Jg(a);return c.call(d,b)};
hba=function(a,b){if(a.Tg)return!0;if(!Hg){var c=b||g.q("window.event"),d=new g.rg(c,this),e=!0;if(!(0>c.keyCode||void 0!=c.returnValue)){a:{var f=!1;if(0==c.keyCode)try{c.keyCode=-1;break a}catch(p){f=!0}if(f||void 0==c.returnValue)c.returnValue=!0}c=[];for(f=d.currentTarget;f;f=f.parentNode)c.push(f);for(var f=a.type,k=c.length-1;!d.Zf&&0<=k;k--){d.currentTarget=c[k];var l=Mg(c[k],f,!0,d),e=e&&l}for(k=0;!d.Zf&&k<c.length;k++)d.currentTarget=c[k],l=Mg(c[k],f,!1,d),e=e&&l}return e}return Lg(a,new g.rg(b,
this))};
g.Dg=function(a){a=a[Eg];return a instanceof vg?a:null};
g.Bg=function(a){if(g.ma(a))return a;a[Ng]||(a[Ng]=function(b){return a.handleEvent(b)});
return a[Ng]};
g.Og=function(){g.mb.call(this);this.Y=new vg(this);this.ox=this;this.so=null};
Pg=function(a,b,c,d){b=a.Y.A[String(b)];if(!b)return!0;b=b.concat();for(var e=!0,f=0;f<b.length;++f){var k=b[f];if(k&&!k.Tg&&k.vh==c){var l=k.listener,p=k.od||k.src;k.Ni&&yg(a.Y,k);e=!1!==l.call(p,d)&&e}}return e&&0!=d.hv};
g.Qg=function(a,b,c){if(g.ma(a))c&&(a=(0,g.r)(a,c));else if(a&&"function"==typeof a.handleEvent)a=(0,g.r)(a.handleEvent,a);else throw Error("Invalid listener argument");return 2147483647<Number(b)?-1:g.m.setTimeout(a,b||0)};
g.Rg=function(a){g.m.clearTimeout(a)};
g.Sg=function(a,b,c){g.mb.call(this);this.A=a;this.B=b||0;this.C=c;this.Gc=(0,g.r)(this.Rl,this)};
nba=function(){Tg++;var a=g.xc(),b=new g.Ce(0,0,a.width,a.height);Te("vps",a.width+"."+a.height);g.Re("vpc");var a=window.document.querySelectorAll(".yt-lockup-thumbnail img[data-ytimg]"),c=a.length,d=[],e=!0;Ug.start();for(var f=0;f<c;f++){var k=a[f];if(Vg(k,b)){var l=iba(k);l.then(jba);d.push(l);Wg.push(l);k.loadTime||(e=!1)}}e&&Te("yt_eil",1);Te("vpni",d.length);g.Re("vpcc");b=g.dd(d).then(kba);g.fd(b,lba);b.then(mba);Wg.push(b);return b};
mba=function(){Ug.stop()};
lba=function(){g.Re("vpr")};
Vg=function(a,b){for(var c=a,d=window.document.body;c!=d;){var e=g.Lc(c);if(e in Xg)break;var f=window.getComputedStyle(c);if("none"==f.display||"hidden"==f.visibility)return!1;f=c.getBoundingClientRect();if(!(b.left<=f.left+f.width&&f.left<=b.left+b.width&&b.top<=f.top+f.height&&f.top<=b.top+b.height))return!1;Xg[e]=!0;c=c.parentElement}return!0};
kba=function(a){for(var b=g.xc(),b=new g.Ce(0,0,b.width,b.height),c=0,d=0,e=a.length;d<e;d++){var f=a[d].time;Vg(a[d].C,b)&&c<f&&(c=f)}return c};
iba=function(a){var b=Tg;return new g.Zc(function(c,d){var e={C:a,time:0};if(a.loadTime)e.time=(0,window.parseInt)(a.loadTime,10),c(e);else{var f=g.G(a,"load",function(){Tg!=b&&(g.$d(f),d());if(a.loadTime){var k=(0,window.parseInt)(a.loadTime,10);g.$d(f);e.time=k;c(e)}});
Yg.push(f)}})};
jba=function(a){Ug.start();Te("vpil",++Zg);a=a.time;$g<a&&($g=a,g.Re("lim",a))};
oba=function(){g.Re("vptl",$g);g.Re("vpl",$g)};
bh=function(){g.Re("ol");window.requestAnimationFrame&&!window.document.hidden?window.requestAnimationFrame(function(){(0,window.setTimeout)(function(){g.Re("cpt")},0)}):window.document.hidden?g.Re("cpt"):(0,window.setTimeout)(function(){g.Re("cpt")},0);
pba();g.x("CSI_VIEWPORT")&&(ah=nba(),ah.then(function(a){g.Re("vpl",a);ah=null},function(){}))};
pba=function(){ch("init");var a=g.x("PAGE_NAME",void 0);a&&ch("init-"+a)};
ch=function(a){g.Jb()?dh.push(g.Kb(g.t(g.Ib,a),0)):g.A(a)};
eh=function(){g.Nb(dh);dh.length=0;for(var a=Wg.length,b=0;b<a;b++)Wg[b].cancel();$g=Zg=Wg.length=0;Xg={};g.$d(Yg);Yg.length=0;ah&&(ah.cancel(),ah=null);(a=g.x("PAGE_NAME",void 0))&&g.Ib("dispose-"+a);g.Ib("dispose")};
qba=function(){bh()};
rba=function(){g.x("TIMING_REPORT_ON_UNLOAD")&&g.Qe(!0);kf("u");eh();g.Ib("pageunload")};
fh=function(){be()};
gh=function(a){a=a.detail.url;window.yt_spf_loaded_history=!0;be();var b=g.ee();if(b&&a){var c=g.td(b.visualElement),b={csn:b.clientScreenNonce};"trackingParams"in c?b.itct=c.trackingParams:(b.veType=c.veType,b.veCounter=c.veCounter);g.sf(a,b)}};
lh=function(){hh=1;ih=jh=0;g.x("TIMING_REPORT_ON_UNLOAD")&&g.Qe(!0);kf("n");Ye();Ue("n");Ke("nr");kh(sba);g.Ib("navigate")};
ph=function(a){a=a.detail.part||a.detail.partial;g.Re("nc"+jh);++jh;if(a.data&&a.data.deferDispose)"watch"==a.name&&g.Re("bc");else{var b=1==hh;hh=2;b?(kh(tba),mh()):kh(uba);if(b=a.data&&a.data.swfcfg)nh(a.timing,b.args),oh(b)}};
qh=function(){g.Re("np"+ih);++ih};
rh=function(a){a=a.detail.response;var b=1==hh;hh=3;b&&(kh(vba),mh());if(b=a.data&&a.data.swfcfg)nh(a.timing,b.args),oh(b)};
uh=function(a){g.Re("nd");a=a.detail.response;g.sh=a.cacheKey;a=a.timing;var b=window._spf_state;Te("yt_nav",b&&b["nav-counter"]||0);Ue("ne",a.responseStart);Te("srt",Math.max(0,a.responseStart-a.navigationStart));Te("yt_lt",a.spfCached?"hot":"warm");Te("yt_pft",+!!a.spfPrefetched);g.Re("pfs",a.fetchStart);g.Re("pfrs",a.responseStart);"redirectStart"in a&&Ze(a);kh(th);window.document.getElementById("content").style.height="";bh();hh=0};
vh=function(a){var b=a.detail.url;if(a=a.detail.err)a.message&&(a.message+=" (url: "+b+")"),g.zb(a)};
wh=function(a){g.tf(g.qe({spfreload:"1",url:a.detail.url,reason:a.detail.reason}))};
xba=function(){wba();g.tb("SERVED_VIA_SPF_HISTORY",!!window.yt_spf_loaded_history);window.yt_spf_loaded_history=!1};
yba=function(){};
mh=function(){var a=window.document.getElementById("content");-1<a.className.indexOf("spf-animate")&&(a.style.height=a.clientHeight+"px");eh();var a=g.x("TIMING_ACTION"),b;for(b in g.sb)delete g.sb[b];g.tb("PREVIOUS_ACTION",a);g.n("ytplayer.config",null,void 0);if((b=g.mg())&&b.stopVideo){if(b.stopVideo(),b=b.getLastError())pg=b,(b=g.D("movie_player"))&&b.stopVideo?(b.stopVideo(),pg="recovered"):pg="missing2"}else pg="missing";lg()};
oh=function(a){"cfg"in Me(void 0)||g.Re("cfg");jg(a)};
kh=function(a){var b=window.document.getElementById("progress");b||(b=window.document.createElement("div"),b.id="progress",b.appendChild(window.document.createElement("dt")),b.appendChild(window.document.createElement("dd")),window.document.body.appendChild(b));g.Mb(xh);xh=g.Lb(function(){var c=a[0],d=a[1],e=a[2];b.className="";var f=b.style;f.transitionDuration=f.webkitTransitionDuration=c+"ms";f.width=d+"%";g.xb(yh);yh=g.vb(function(){b.className=e},c)},0)};
wba=function(){var a=th[0]+50;g.xb(yh);yh=g.vb(function(){var a=window.document.getElementById("progress");a&&a.parentNode.removeChild(a)},a)};
nh=function(a,b){var c=a&&a.spfCached,d=a&&a.spfPrefetched,e=[];c&&!d&&(0,g.z)(zba,function(a){a in b&&(delete b[a],e.push(a))});
g.x("EXP_DEBUG_PREFETCH")&&(e.sort(),c={a:"removeNonCacheableVideoVars",cached:c,prefetched:d,deleted:e.join("")},g.tf(g.qe(c)))};
Cba=function(a){g.zh&&!g.Ah&&!g.Bh&&!g.Ch&&a.pushManager&&("default"!=window.Notification.permission?Dh(a).then(Aba):g.x("SERVICE_WORKER_PROMPT_NOTIFICATIONS",void 0)&&Bba(a))};
Bba=function(a){a&&g.x("LOGGED_IN",void 0)&&window.Notification.requestPermission().then(function(b){"granted"==b?Dh(a).then(Eh):"denied"==b&&Eh()})};
Dh=function(a){return a.pushManager.getSubscription().then(function(b){return b?window.Promise.resolve():a.pushManager.subscribe({userVisibleOnly:!0}).then(function(){return window.Promise.resolve()})})};
Eh=function(){window.navigator.serviceWorker.controller.postMessage({type:"notifications_register",data:g.x("ID_TOKEN")})};
Aba=function(){window.navigator.serviceWorker.controller.postMessage({type:"notifications_check_user",data:g.x("ID_TOKEN")})};
Dba=function(){var a="/sw.js",b=g.x("SERVICE_WORKER_VFL",void 0);b&&(a+="?vfl="+b);window.navigator.serviceWorker.register(a,{scope:"/"});g.Oc("service_worker_push_enabled")&&window.navigator.serviceWorker.ready.then(Cba)};
Eba=function(a){a&&window.navigator.serviceWorker.register("/sw.js?0",{scope:"/"})};
Fh=function(){g.Ob.call(this,"www/base");this.B=0};
Gh=function(a){(a=a.detail.name)&&Rb(a)};
g.aa=[];g.Hh=g.Hh||{};g.m=this;oa="closure_uid_"+(1E9*Math.random()>>>0);aaa=0;g.F=Date.now||function(){return+new Date};qa[" "]=g.ea;g.v(g.ta,Error);g.ta.prototype.name="CustomError";var eaa,faa,gaa,haa,iaa,jaa,daa;g.Aa=String.prototype.trim?function(a){return a.trim()}:function(a){return a.replace(/^[\s\xa0]+|[\s\xa0]+$/g,"")};
eaa=/&/g;faa=/</g;gaa=/>/g;haa=/"/g;iaa=/'/g;jaa=/\x00/g;daa=/[\x00&<>"']/;g.Ih=String.prototype.repeat?function(a,b){return a.repeat(b)}:function(a,b){return Array(b+1).join(a)};
g.Fba=2147483648*Math.random()|0;g.Ha=Array.prototype.indexOf?function(a,b,c){return Array.prototype.indexOf.call(a,b,c)}:function(a,b,c){c=null==c?0:0>c?Math.max(0,a.length+c):c;
if(g.ja(a))return g.ja(b)&&1==b.length?a.indexOf(b,c):-1;for(;c<a.length;c++)if(c in a&&a[c]===b)return c;return-1};
g.Gba=Array.prototype.lastIndexOf?function(a,b,c){return Array.prototype.lastIndexOf.call(a,b,null==c?a.length-1:c)}:function(a,b,c){c=null==c?a.length-1:c;
0>c&&(c=Math.max(0,a.length+c));if(g.ja(a))return g.ja(b)&&1==b.length?a.lastIndexOf(b,c):-1;for(;0<=c;c--)if(c in a&&a[c]===b)return c;return-1};
g.z=Array.prototype.forEach?function(a,b,c){Array.prototype.forEach.call(a,b,c)}:function(a,b,c){for(var d=a.length,e=g.ja(a)?a.split(""):a,f=0;f<d;f++)f in e&&b.call(c,e[f],f,a)};
g.Jh=Array.prototype.filter?function(a,b,c){return Array.prototype.filter.call(a,b,c)}:function(a,b,c){for(var d=a.length,e=[],f=0,k=g.ja(a)?a.split(""):a,l=0;l<d;l++)if(l in k){var p=k[l];
b.call(c,p,l,a)&&(e[f++]=p)}return e};
g.cf=Array.prototype.map?function(a,b,c){return Array.prototype.map.call(a,b,c)}:function(a,b,c){for(var d=a.length,e=Array(d),f=g.ja(a)?a.split(""):a,k=0;k<d;k++)k in f&&(e[k]=b.call(c,f[k],k,a));
return e};
g.Kh=Array.prototype.reduce?function(a,b,c,d){d&&(b=(0,g.r)(b,d));return Array.prototype.reduce.call(a,b,c)}:function(a,b,c,d){var e=c;
(0,g.z)(a,function(c,k){e=b.call(d,e,c,k,a)});
return e};
g.Lh=Array.prototype.some?function(a,b,c){return Array.prototype.some.call(a,b,c)}:function(a,b,c){for(var d=a.length,e=g.ja(a)?a.split(""):a,f=0;f<d;f++)if(f in e&&b.call(c,e[f],f,a))return!0;
return!1};
g.Mh=Array.prototype.every?function(a,b,c){return Array.prototype.every.call(a,b,c)}:function(a,b,c){for(var d=a.length,e=g.ja(a)?a.split(""):a,f=0;f<d;f++)if(f in e&&!b.call(c,e[f],f,a))return!1;
return!0};g.Nh=g.Ma(!1);g.Oh=g.Ma(!0);g.Ph=g.Ma(null);var Va="constructor hasOwnProperty isPrototypeOf propertyIsEnumerable toLocaleString toString valueOf".split(" ");a:{var Qh=g.m.navigator;if(Qh){var Rh=Qh.userAgent;if(Rh){g.Xa=Rh;break a}}g.Xa=""};var lb;bb.prototype.get=function(){var a;0<this.C?(this.C--,a=this.A,this.A=a.next,a.next=null):a=this.B();return a};var ib=new bb(function(){return new eb},function(a){a.reset()},100);
db.prototype.remove=function(){var a=null;this.A&&(a=this.A,this.A=this.A.next,this.A||(this.C=null),a.next=null);return a};
eb.prototype.set=function(a,b){this.Bc=a;this.scope=b;this.next=null};
eb.prototype.reset=function(){this.next=this.scope=this.Bc=null};var fb,gb=!1,hb=new db;g.mb.prototype.Nd=!1;g.mb.prototype.fb=function(){return this.Nd};
g.mb.prototype.dispose=function(){this.Nd||(this.Nd=!0,this.U())};
g.mb.prototype.U=function(){if(this.Jb)for(;this.Jb.length;)this.Jb.shift()()};g.v(g.qb,g.mb);g.h=g.qb.prototype;g.h.subscribe=function(a,b,c){var d=this.sd[a];d||(d=this.sd[a]=[]);var e=this.D;this.A[e]=a;this.A[e+1]=b;this.A[e+2]=c;this.D=e+3;d.push(e);return e};
g.h.unsubscribe=function(a,b,c){if(a=this.sd[a]){var d=this.A;if(a=g.Ga(a,function(a){return d[a+1]==b&&d[a+2]==c}))return this.td(a)}return!1};
g.h.td=function(a){var b=this.A[a];if(b){var c=this.sd[b];0!=this.B?(this.C.push(a),this.A[a+1]=g.ea):(c&&g.Ka(c,a),delete this.A[a],delete this.A[a+1],delete this.A[a+2])}return!!b};
g.h.Ea=function(a,b){var c=this.sd[a];if(c){for(var d=Array(arguments.length-1),e=1,f=arguments.length;e<f;e++)d[e-1]=arguments[e];if(this.F)for(e=0;e<c.length;e++){var k=c[e];maa(this.A[k+1],this.A[k+2],d)}else{this.B++;try{for(e=0,f=c.length;e<f;e++)k=c[e],this.A[k+1].apply(this.A[k+2],d)}finally{if(this.B--,0<this.C.length&&0==this.B)for(;c=this.C.pop();)this.td(c)}}return 0!=e}return!1};
g.h.clear=function(a){if(a){var b=this.sd[a];b&&((0,g.z)(b,this.td,this),delete this.sd[a])}else this.A.length=0,this.sd={}};
g.h.nb=g.ca(3);g.h.U=function(){g.qb.L.U.call(this);this.clear();this.C.length=0};g.sb=window.yt&&window.yt.config_||window.ytcfg&&window.ytcfg.data_||{};g.n("yt.config_",g.sb,void 0);g.n("yt.tokens_",window.yt&&window.yt.tokens_||{},void 0);g.Ab=window.yt&&window.yt.msgs_||g.q("window.ytcfg.msgs")||{};g.n("yt.msgs_",g.Ab,void 0);g.Bd=window.performance&&window.performance.timing&&window.performance.now?function(){return window.performance.timing.navigationStart+window.performance.now()}:function(){return(new Date).getTime()};
g.Gf="Microsoft Internet Explorer"==window.navigator.appName;var Hba=g.q("yt.pubsub.instance_")||new g.qb;g.qb.prototype.subscribe=g.qb.prototype.subscribe;g.qb.prototype.unsubscribeByKey=g.qb.prototype.td;g.qb.prototype.publish=g.qb.prototype.Ea;g.qb.prototype.clear=g.qb.prototype.clear;g.n("yt.pubsub.instance_",Hba,void 0);var Eb=g.q("yt.pubsub.subscribedKeys_")||{};g.n("yt.pubsub.subscribedKeys_",Eb,void 0);var Gb=g.q("yt.pubsub.topicToKeys_")||{};g.n("yt.pubsub.topicToKeys_",Gb,void 0);var Fb=g.q("yt.pubsub.isSynchronous_")||{};
g.n("yt.pubsub.isSynchronous_",Fb,void 0);var Db=g.q("yt.pubsub.skipSubId_")||null;g.n("yt.pubsub.skipSubId_",Db,void 0);g.h=g.Ob.prototype;g.h.wN=function(){this.Oj()||this.init()};
g.h.enable=function(){this.A=1;(0,g.z)("string"==typeof this.page?[this.page]:this.page,function(a){a&&(this.subscribe("init-"+a,this.wN,this),this.subscribe("dispose-"+a,this.dispose,this),g.x("PAGE_NAME")==a&&g.Pb(this))},this)};
g.h.init=function(){g.Mb(this.C);this.A=2;this.H&&this.H()};
g.h.Oj=function(){return 2==this.A};
g.h.dispose=function(){this.A=3;g.Mb(this.C);this.F&&this.F()};
g.h.disable=function(){this.A=4;this.clear();try{this.dispose()}catch(a){g.zb(a)}};
g.h.subscribe=function(a,b,c){a=g.y(a,b,c);this.D.push(a);return a};
g.h.clear=function(){g.Hb(this.D);this.D=[]};var Qb=g.q("yt.modules.registry_")||{};g.n("yt.modules.registry_",Qb,void 0);g.Iba=RegExp("[A-Za-z\u00c0-\u00d6\u00d8-\u00f6\u00f8-\u02b8\u0300-\u0590\u0800-\u1fff\u200e\u2c00-\ufb1c\ufe00-\ufe6f\ufefd-\uffff]");g.Jba=RegExp("^[^\u0591-\u06ef\u06fa-\u07ff\u200f\ufb1d-\ufdff\ufe70-\ufefc]*[A-Za-z\u00c0-\u00d6\u00d8-\u00f6\u00f8-\u02b8\u0300-\u0590\u0800-\u1fff\u200e\u2c00-\ufb1c\ufe00-\ufe6f\ufefd-\uffff]");g.Sh=RegExp("^[^A-Za-z\u00c0-\u00d6\u00d8-\u00f6\u00f8-\u02b8\u0300-\u0590\u0800-\u1fff\u200e\u2c00-\ufb1c\ufe00-\ufe6f\ufefd-\uffff]*[\u0591-\u06ef\u06fa-\u07ff\u200f\ufb1d-\ufdff\ufe70-\ufefc]");g.Ub.prototype.Sf=!0;g.Tb={};g.Ub.prototype.Se=function(){return this.A};
g.Kba=g.Vb("");g.Xb.prototype.Sf=!0;g.Xb.prototype.Se=function(){return this.A};
g.Xb.prototype.xm=!0;g.Xb.prototype.Qe=g.ca(5);var oaa=/^(?:(?:https?|mailto|ftp):|[^&:/?#]*(?:[/?#]|$))/i,Wb={};g.Zb("about:blank");g.dc.prototype.xm=!0;g.dc.prototype.Qe=g.ca(4);g.dc.prototype.Sf=!0;g.dc.prototype.Se=function(){return this.A};
g.cc={};g.Lba=g.ec("<!DOCTYPE html>",0);g.Th=g.ec("",0);g.Uh=g.ec("<br>",0);var hc={};var paa=/\.vflset|-vfl[a-zA-Z0-9_+=-]+/,qaa=/-[a-zA-Z]{2,3}_[a-zA-Z]{2,3}(?=(\/|$))/;g.Mba=Math.sign||function(a){return 0<a?1:0>a?-1:a};g.h=g.lc.prototype;g.h.clone=function(){return new g.lc(this.x,this.y)};
g.h.ceil=function(){this.x=Math.ceil(this.x);this.y=Math.ceil(this.y);return this};
g.h.floor=function(){this.x=Math.floor(this.x);this.y=Math.floor(this.y);return this};
g.h.round=function(){this.x=Math.round(this.x);this.y=Math.round(this.y);return this};
g.h.scale=function(a,b){var c=g.ka(b)?b:a;this.x*=a;this.y*=c;return this};g.h=g.mc.prototype;g.h.clone=function(){return new g.mc(this.width,this.height)};
g.h.og=function(){return this.width*this.height};
g.h.aspectRatio=function(){return this.width/this.height};
g.h.isEmpty=function(){return!this.og()};
g.h.ceil=function(){this.width=Math.ceil(this.width);this.height=Math.ceil(this.height);return this};
g.h.floor=function(){this.width=Math.floor(this.width);this.height=Math.floor(this.height);return this};
g.h.round=function(){this.width=Math.round(this.width);this.height=Math.round(this.height);return this};
g.h.scale=function(a,b){var c=g.ka(b)?b:a;this.width*=a;this.height*=c;return this};var ai,bi,raa,fi;g.Vh=g.Ya("Opera");g.E=g.Za();g.Wh=g.Ya("Edge");g.Xh=g.Wh||g.E;g.Yh=g.Ya("Gecko")&&!(g.ya(g.Xa.toLowerCase(),"webkit")&&!g.Ya("Edge"))&&!(g.Ya("Trident")||g.Ya("MSIE"))&&!g.Ya("Edge");g.Bc=g.ya(g.Xa.toLowerCase(),"webkit")&&!g.Ya("Edge");g.Bc&&g.Ya("Mobile");g.Zh=g.Ya("Macintosh");g.$h=g.Ya("Windows");g.Nba=g.Ya("Linux")||g.Ya("CrOS");ai=g.m.navigator||null;ai&&g.ya(ai.appVersion||"","X11");g.Oba=g.Ya("Android");g.Bh=g.nc();g.Ch=g.Ya("iPad");g.Pba=g.Ya("iPod");
a:{var ci="",di=function(){var a=g.Xa;if(g.Yh)return/rv\:([^\);]+)(\)|;)/.exec(a);if(g.Wh)return/Edge\/([\d\.]+)/.exec(a);if(g.E)return/\b(?:MSIE|rv)[: ]([^\);]+)(\)|;)/.exec(a);if(g.Bc)return/WebKit\/(\S+)/.exec(a);if(g.Vh)return/(?:Version)[ \/]?(\S+)/.exec(a)}();
di&&(ci=di?di[1]:"");if(g.E){var ei=oc();if(null!=ei&&ei>(0,window.parseFloat)(ci)){bi=String(ei);break a}}bi=ci}g.pc=bi;raa={};fi=g.m.document;g.rc=fi&&g.E?oc()||("CSS1Compat"==fi.compatMode?(0,window.parseInt)(g.pc,10):5):void 0;var saa;saa=!g.E||g.sc(9);g.Qba=!g.Yh&&!g.E||g.E&&g.sc(9)||g.Yh&&g.qc("1.9.1");g.gi=g.E&&!g.qc("9");g.Rba=g.E||g.Vh||g.Bc;g.Sba=g.E&&!g.sc(9);var uc={cellpadding:"cellPadding",cellspacing:"cellSpacing",colspan:"colSpan",frameborder:"frameBorder",height:"height",maxlength:"maxLength",nonce:"nonce",role:"role",rowspan:"rowSpan",type:"type",usemap:"useMap",valign:"vAlign",width:"width"};var waa=g.Bc?"webkit":g.Yh?"moz":g.E?"ms":g.Vh?"o":"",Kc=g.q("yt.dom.getNextId_");if(!Kc){Kc=function(){return++Tba};
g.n("yt.dom.getNextId_",Kc,void 0);var Tba=0};g.Rc.prototype.Tb=function(a){var b=[];Tc(this,a,b);return b.join("")};
var Vc={'"':'\\"',"\\":"\\\\","/":"\\/","\b":"\\b","\f":"\\f","\n":"\\n","\r":"\\r","\t":"\\t","\x0B":"\\u000b"},xaa=/\uffff/.test("\uffff")?/[\\\"\x00-\x1f\x7f-\uffff]/g:/[\\\"\x00-\x1f\x7f-\xff]/g;$c.prototype.reset=function(){this.context=this.C=this.B=this.A=null;this.D=!1};
var ad=new bb(function(){return new $c},function(a){a.reset()},100);
g.Zc.prototype.then=function(a,b,c){return ed(this,g.ma(a)?a:null,g.ma(b)?b:null,c)};
g.Wc(g.Zc);g.Zc.prototype.cancel=function(a){0==this.A&&jb(function(){var b=new g.ld(a);gd(this,b)},this)};
g.Zc.prototype.R=function(a){this.A=0;g.Yc(this,2,a)};
g.Zc.prototype.Y=function(a){this.A=0;g.Yc(this,3,a)};
g.Zc.prototype.G=function(){for(var a;a=hd(this);)id(this,a,this.A,this.K);this.H=!1};
var nd=ab;g.v(g.ld,g.ta);g.ld.prototype.name="cancel";var qd=null;rd.prototype.D=function(){var a=g.q("gapi.config.update");a("googleapis.config/auth/useFirstPartyAuth",!0);var b=this.A.apiaryHost;g.va(g.za(b))||a("googleapis.config/root",(-1==b.indexOf("://")?"//":"")+b);b=this.A.np;g.va(g.za(b))||a("googleapis.config/root-1p",(-1==b.indexOf("://")?"//":"")+b);a("googleapis.config/sessionIndex",g.x("SESSION_INDEX"));g.q("gapi.client.setApiKey")(this.A.innertubeApiKey)};
rd.prototype.C=function(){return{context:g.pd(this.A)}};
rd.prototype.B=function(a,b,c){var d,e=!1;0<c.timeout&&(d=g.vb(function(){e||(e=!0,c.lc&&c.lc())},c.timeout));
Caa(this,a,b,function(a){if(!e)if(e=!0,d&&g.xb(d),a)c.W&&c.W(a);else if(c.onError)c.onError()})};var Daa,vd;Daa={log_event:"events",log_interaction:"interactions"};g.Ad={};vd={};g.zd=0;g.ud=g.q("yt.logging.transport.logsQueue_")||{};g.n("yt.logging.transport.logsQueue_",g.ud,void 0);g.Ed="StopIteration"in g.m?g.m.StopIteration:{message:"StopIteration",stack:""};g.Dd.prototype.next=function(){throw g.Ed;};
g.Dd.prototype.fc=function(){return this};g.v(g.Id,Eaa);g.Id.prototype.nb=g.ca(2);g.Id.prototype.clear=function(){var a=g.Hd(this.fc(!0)),b=this;(0,g.z)(a,function(a){b.remove(a)})};g.v(g.Jd,g.Id);g.h=g.Jd.prototype;g.h.isAvailable=function(){if(!this.A)return!1;try{return this.A.setItem("__sak","1"),this.A.removeItem("__sak"),!0}catch(a){return!1}};
g.h.set=function(a,b){try{this.A.setItem(a,b)}catch(c){if(0==this.A.length)throw"Storage mechanism: Storage disabled";throw"Storage mechanism: Quota exceeded";}};
g.h.get=function(a){a=this.A.getItem(a);if(!g.ja(a)&&null!==a)throw"Storage mechanism: Invalid value was encountered";return a};
g.h.remove=function(a){this.A.removeItem(a)};
g.h.nb=g.ca(1);g.h.fc=function(a){var b=0,c=this.A,d=new g.Dd;d.next=function(){if(b>=c.length)throw g.Ed;var d=c.key(b++);if(a)return d;d=c.getItem(d);if(!g.ja(d))throw"Storage mechanism: Invalid value was encountered";return d};
return d};
g.h.clear=function(){this.A.clear()};
g.h.key=function(a){return this.A.key(a)};g.v(g.Kd,g.Jd);g.v(Ld,g.Jd);g.Md.prototype.set=function(a,b){g.da(b)?this.A.set(a,g.Sc(b)):this.A.remove(a)};
g.Md.prototype.get=function(a){var b;try{b=this.A.get(a)}catch(c){return}if(null!==b)try{return g.Qc(b)}catch(c){throw"Storage: Invalid value was encountered";}};
g.Md.prototype.remove=function(a){this.A.remove(a)};g.v(Nd,g.Md);Nd.prototype.set=function(a,b){Nd.L.set.call(this,a,Pd(b))};
Nd.prototype.C=function(a){a=Nd.L.get.call(this,a);if(!g.da(a)||a instanceof Object)return a;throw"Storage: Invalid value was encountered";};
Nd.prototype.get=function(a){if(a=this.C(a)){if(a=a.data,!g.da(a))throw"Storage: Invalid value was encountered";}else a=void 0;return a};g.v(g.Qd,Nd);g.Qd.prototype.set=function(a,b,c){if(b=Pd(b)){if(c){if(c<(0,g.F)()){g.Qd.prototype.remove.call(this,a);return}b.expiration=c}b.creation=(0,g.F)()}g.Qd.L.set.call(this,a,b)};
g.Qd.prototype.C=function(a,b){var c=g.Qd.L.C.call(this,a);if(c)if(!b&&g.Rd(c))g.Qd.prototype.remove.call(this,a);else return c};g.v(g.Sd,g.Qd);var hi,ii;hi=new g.Kd;g.Ud=hi.isAvailable()?new g.Sd(hi):null;ii=new Ld;g.Td=ii.isAvailable()?new g.Sd(ii):null;g.Rf=g.Ya("Firefox");g.ji=g.nc()||g.Ya("iPod");g.ki=g.Ya("iPad");g.Ah=g.Ya("Android")&&!(g.$a()||g.Ya("Firefox")||g.Ya("Opera")||g.Ya("Silk"));g.zh=g.$a();g.li=g.Ya("Safari")&&!(g.$a()||g.Ya("Coast")||g.Ya("Opera")||g.Ya("Edge")||g.Ya("Silk")||g.Ya("Android"))&&!(g.nc()||g.Ya("iPad")||g.Ya("iPod"));g.Uba=g.Yh||g.Bc&&!g.li||g.Vh||"function"==typeof g.m.btoa;g.Wd.prototype.preventDefault=function(){this.event&&(this.event.returnValue=!1,this.event.preventDefault&&this.event.preventDefault())};
g.Wd.prototype.stopPropagation=function(){this.event&&(this.event.cancelBubble=!0,this.event.stopPropagation&&this.event.stopPropagation())};
g.Wd.prototype.stopImmediatePropagation=function(){this.event&&(this.event.cancelBubble=!0,this.event.stopImmediatePropagation&&this.event.stopImmediatePropagation())};
var Faa={stopImmediatePropagation:1,stopPropagation:1,preventMouseEvent:1,preventManipulation:1,preventDefault:1,layerX:1,layerY:1,scale:1,rotation:1,webkitMovementX:1,webkitMovementY:1};g.Xd=g.q("yt.events.listeners_")||{};g.n("yt.events.listeners_",g.Xd,void 0);var Zd=g.q("yt.events.counter_")||{count:0};g.n("yt.events.counter_",Zd,void 0);g.ie=/^(?:([^:/?#.]+):)?(?:\/\/(?:([^/?#]*)@)?([^/#?]*?)(?::([0-9]+))?(?=[/#?]|$))?([^?#]+)?(?:\?([^#]*))?(?:#([\s\S]*))?$/;var ue={},Haa=0;g.ve.prototype.Tb=function(){return{version:this.version,args:this.args}};
g.we.prototype.toString=function(){return this.topic};var Vba=g.q("yt.pubsub2.instance_")||new g.qb;g.qb.prototype.subscribe=g.qb.prototype.subscribe;g.qb.prototype.unsubscribeByKey=g.qb.prototype.td;g.qb.prototype.publish=g.qb.prototype.Ea;g.qb.prototype.clear=g.qb.prototype.clear;g.n("yt.pubsub2.instance_",Vba,void 0);g.mi=g.q("yt.pubsub2.subscribedKeys_")||{};g.n("yt.pubsub2.subscribedKeys_",g.mi,void 0);g.ni=g.q("yt.pubsub2.topicToKeys_")||{};g.n("yt.pubsub2.topicToKeys_",g.ni,void 0);g.oi=g.q("yt.pubsub2.isAsync_")||{};
g.n("yt.pubsub2.isAsync_",g.oi,void 0);g.n("yt.pubsub2.skipSubKey_",null,void 0);var jf=(0,g.F)().toString();var Je=window.performance||window.mozPerformance||window.msPerformance||window.webkitPerformance||{};g.v(ze,g.ve);var Taa=new g.we("timing-sent",ze);g.h=g.Ae.prototype;g.h.getHeight=function(){return this.bottom-this.top};
g.h.clone=function(){return new g.Ae(this.top,this.right,this.bottom,this.left)};
g.h.contains=function(a){return g.Be(this,a)};
g.h.ceil=function(){this.top=Math.ceil(this.top);this.right=Math.ceil(this.right);this.bottom=Math.ceil(this.bottom);this.left=Math.ceil(this.left);return this};
g.h.floor=function(){this.top=Math.floor(this.top);this.right=Math.floor(this.right);this.bottom=Math.floor(this.bottom);this.left=Math.floor(this.left);return this};
g.h.round=function(){this.top=Math.round(this.top);this.right=Math.round(this.right);this.bottom=Math.round(this.bottom);this.left=Math.round(this.left);return this};
g.h.scale=function(a,b){var c=g.ka(b)?b:a;this.left*=a;this.right*=a;this.top*=c;this.bottom*=c;return this};g.h=g.Ce.prototype;g.h.clone=function(){return new g.Ce(this.left,this.top,this.width,this.height)};
g.h.contains=function(a){return a instanceof g.lc?a.x>=this.left&&a.x<=this.left+this.width&&a.y>=this.top&&a.y<=this.top+this.height:this.left<=a.left&&this.left+this.width>=a.left+a.width&&this.top<=a.top&&this.top+this.height>=a.top+a.height};
g.h.ceil=function(){this.left=Math.ceil(this.left);this.top=Math.ceil(this.top);this.width=Math.ceil(this.width);this.height=Math.ceil(this.height);return this};
g.h.floor=function(){this.left=Math.floor(this.left);this.top=Math.floor(this.top);this.width=Math.floor(this.width);this.height=Math.floor(this.height);return this};
g.h.round=function(){this.left=Math.round(this.left);this.top=Math.round(this.top);this.width=Math.round(this.width);this.height=Math.round(this.height);return this};
g.h.scale=function(a,b){var c=g.ka(b)?b:a;this.left*=a;this.width*=a;this.top*=c;this.height*=c;return this};He.prototype.toString=function(){return this.region.toString()+": "+this.timing+" => "+this.url};
Ie.prototype.toString=function(){return["progress",this.progress,"timing",this.timing,"area",this.og].join(": ")};
Ge.C=.1;Ge.A=/url\(["']?(http[^'"\)]+)['"]?\)/i;Ge.B="mark_iframe_loaded: ";Ge.D=20;var Raa={vc:!0},Kaa=/^mark_/i,af={'script[name="scheduler/scheduler"]':"sj",'script[name="player/base"]':"pj",'link[rel="stylesheet"][name="www-player"]':"pc",'script[name="desktop_polymer/desktop_polymer"]':"dpj",'link[rel="import"][name="desktop_polymer"]':"dph",'script[name="mobile_polymer/mobile_polymer"]':"mpj",'link[rel="import"][name="mobile_polymer"]':"mph",'script[name="player-plasma-phone/base"]':"mpppj",'script[name="player-plasma-tablet/base"]':"mpptj",'link[rel="stylesheet"][name="mobile-polymer-player"]':"mppc"},
Ve={ad_at:"adType",cpn:"clientPlaybackNonce",csn:"clientScreenNonce",yt_lt:"loadType",yt_ad:"isMonetized",yt_ad_pr:"prerollAllowed",yt_red:"isRedSubscriber",yt_vis:"isVisible"},Maa=["isMonetized","prerollAllowed","isRedSubscriber","isVisible"],Naa=(0,g.r)(Je.clearResourceTimings||Je.webkitClearResourceTimings||Je.mozClearResourceTimings||Je.msClearResourceTimings||Je.oClearResourceTimings||g.ea,Je);g.mf=/\s*;\s*/;g.h=g.lf.prototype;g.h.isEnabled=function(){return window.navigator.cookieEnabled};
g.h.set=function(a,b,c,d,e,f){if(/[;=\s]/.test(a))throw Error('Invalid cookie name "'+a+'"');if(/[;\r\n]/.test(b))throw Error('Invalid cookie value "'+b+'"');g.da(c)||(c=-1);e=e?";domain="+e:"";d=d?";path="+d:"";f=f?";secure":"";c=0>c?"":0==c?";expires="+(new Date(1970,1,1)).toUTCString():";expires="+(new Date((0,g.F)()+1E3*c)).toUTCString();this.A.cookie=a+"="+b+e+d+c+f};
g.h.get=function(a,b){for(var c=a+"=",d=(this.A.cookie||"").split(g.mf),e=0,f;f=d[e];e++){if(0==f.lastIndexOf(c,0))return f.substr(c.length);if(f==a)return""}return b};
g.h.remove=function(a,b,c){var d=g.da(this.get(a));this.set(a,"",0,b,c);return d};
g.h.Lb=g.ca(6);g.h.mb=g.ca(7);g.h.isEmpty=function(){return!this.A.cookie};
g.h.nb=g.ca(0);g.h.oe=g.ca(8);g.h.clear=function(){for(var a=g.nf(this).keys,b=a.length-1;0<=b;b--)this.remove(a[b])};
g.of=new g.lf("undefined"==typeof window.document?null:window.document);g.of.C=3950;var Uaa={enablejsapi:1},Vaa={},Waa={allowscriptaccess:"always",allowfullscreen:"true",bgcolor:"#000000"};uf.prototype.clone=function(){var a=new uf,b;for(b in this)if(this.hasOwnProperty(b)){var c=this[b];"object"==g.ga(c)?a[b]=g.Ua(c):a[b]=c}return a};g.wf=null;g.pi=g.E?"focusin":"DOMFocusIn";g.qi=g.E?"focusout":"DOMFocusOut";g.ri=g.Bc?"webkitTransitionEnd":g.Vh?"otransitionend":"transitionend";g.si=g.Yh?"MozUserSelect":g.Bc||g.Wh?"WebkitUserSelect":null;g.fa(g.Hf);g.Hf.prototype.getVersion=function(){return[this.major,this.minor,this.A]};var Xaa=/cssbin\/(?:debug-)?([a-zA-Z0-9_-]+?)(?:-2x|-web|-rtl|-vfl|.css)/;var $f;var ti=g.Xa,ti=ti.toLowerCase();if(g.ya(ti,"android")){var ui=ti.match(/android\D*(\d\.\d)[^\;|\)]*[\;\)]/);if(ui)$f=Number(ui[1]);else{var vi={cupcake:1.5,donut:1.6,eclair:2,froyo:2.2,gingerbread:2.3,honeycomb:3,"ice cream sandwich":4,jellybean:4.1},wi=ti.match("("+g.Pa(vi).join("|")+")");$f=wi?vi[wi[0]]:0}}else $f=void 0;var $aa=['video/mp4; codecs="avc1.42001E, mp4a.40.2"','video/webm; codecs="vp8.0, vorbis"'],aba=['audio/mp4; codecs="mp4a.40.2"'];g.v(Nf,g.mb);Nf.prototype.Va=function(a){for(var b=0;b<this.A.length;b++)if(this.A[b]==a){this.A.splice(b,1);a.target.removeEventListener(a.name,a.Kb);break}};
Nf.prototype.U=function(){Pf(this);Nf.L.U.call(this)};var Yaa={"api.invalidparam":2,auth:150,"drm.auth":150,heartbeat:150,"html5.unsupportedads":5,"fmt.noneavailable":5,"fmt.decode":5,"fmt.unplayable":5,"html5.missingapi":5,"html5.unsupportedlive":5,"drm.unavailable":5};g.v(Sf,g.mb);var Zaa=["drm.unavailable","fmt.noneavailable","html5.missingapi","html5.unsupportedads","html5.unsupportedlive"];g.h=Sf.prototype;g.h.getId=function(){return this.ha};
g.h.zo=function(a,b){this.fb()||(Uf(this,a),Yf(this,b),this.H&&Vf(this))};
g.h.hz=function(){return this.ib};
g.h.dP=function(){if(!this.aa){var a=ag(this);a&&"html5"==cg(this)?(this.G="html5",this.H||this.Sg()):(dg(this),this.G="html5",a&&this.M?(this.D.appendChild(this.M),this.Sg()):(this.A.loaded=!0,this.P=(0,g.r)(function(){var a=this.D,c=this.A.clone();g.q("yt.player.Application.create")(a,c);this.Sg()},this),this.aa=!0,a?this.P():(g.jc(this.A.assets.js,this.P),g.Mf(this.A.assets.css))))}};
g.h.cP=function(){var a=this.A.clone();if(!this.F){var b=Xf(this);b&&(this.F=window.document.createElement("span"),this.F.tabIndex=0,Of(this.ea,this.F,"focus",this.Gt),this.R=window.document.createElement("span"),this.R.tabIndex=0,Of(this.ea,this.R,"focus",this.Gt),g.Gc(this.F,b),g.Hc(this.R,b))}a.attrs.width=a.attrs.width||"100%";a.attrs.height=a.attrs.height||"100%";"flash"==cg(this)?(this.G="flash",this.H||this.Sg()):(dg(this),this.G="flash",this.A.loaded=!0,b=g.Hf.getInstance(),b=g.Jf(b)||!g.Kf(b)?
a.url:a.urlV9As2,window!=window.top&&window.document.referrer&&(a.args.framer=window.document.referrer.substring(0,128)),g.Lf(this.D,b,a),this.Sg())};
g.h.Gt=function(){Xf(this).focus()};
g.h.Sg=function(){if(!this.fb()){var a=Xf(this),b=!1;try{a&&a.getApiInterface&&a.getApiInterface()&&(b=!0)}catch(f){}if(b)if(this.aa=!1,a.isNotServable&&a.isNotServable(this.A.args.video_id))Zf(this);else{Qf(this);this.H=!0;a=Xf(this);a.addEventListener&&(this.T=bg(this,a,"addEventListener"));a.removeEventListener&&(this.la=bg(this,a,"removeEventListener"));for(var b=a.getApiInterface(),b=b.concat(a.getInternalApiInterface()),c=0;c<b.length;c++){var d=b[c];this.api[d]||(this.api[d]=bg(this,a,d))}for(var e in this.B)this.T(e,
this.B[e]);Vf(this);this.Ra&&this.Ra(this.api);this.X.Ea("onReady",this.api)}else this.wb=g.vb((0,g.r)(this.Sg,this),50)}};
g.h.rP=function(){return this.H};
g.h.ie=function(a,b){if(!this.fb()){var c=Tf(this,b);if(c){if(!g.Ia(this.Hb,a)&&!this.B[a]){var d=bba(this,a);this.T&&this.T(a,d)}this.X.subscribe(a,c);"onReady"==a&&this.H&&g.vb(g.t(c,this.api),0)}}};
g.h.jN=function(a,b){if(!this.fb()){var c=Tf(this,b);c&&this.X.unsubscribe(a,c)}};
g.h.jy=function(a){a=a?vaa:uaa;for(var b=a(window.document.activeElement);b&&(1!=b.nodeType||b==this.F||b==this.R||(b.focus(),b!=window.document.activeElement));)b=a(b)};
g.h.ep=function(a){g.A("a11y-announce",a)};
g.h.VI=function(a){Zf(this,a)};
g.h.YI=function(a){g.A("WATCH_LATER_VIDEO_ADDED",a)};
g.h.ZI=function(a){g.A("WATCH_LATER_VIDEO_REMOVED",a)};
g.h.CI=function(){this.bb||(g.zh?(this.ab=g.Ac(window.document),Of(this.Y,window,"scroll",this.rL),Of(this.Y,this.D,"touchmove",this.SK)):(Of(this.Y,this.D,"mousewheel",this.Vt),Of(this.Y,this.D,"wheel",this.Vt)),this.bb=!0)};
g.h.DI=function(){Pf(this.Y);this.bb=!1};
g.h.Vt=function(a){g.ae(a)};
g.h.rL=function(){window.scrollTo(this.ab.x,this.ab.y)};
g.h.SK=function(a){a.preventDefault()};
g.h.aA=function(){return this.G||cg(this)};
g.h.Lz=function(){return this.lb};
g.h.cancel=function(){if(this.P){var a=this.P,b=g.ic(this.A.assets.js);window.spf.script.ignore(b,a)}g.xb(this.wb);this.aa=!1};
g.h.U=function(){dg(this);if(this.M&&this.A)try{this.M.destroy()}catch(b){g.zb(b)}this.Wa=null;for(var a in this.B)g.m[this.B[a]]=null;this.ib=this.A=this.api=null;delete this.D;delete this.K;Sf.L.U.call(this)};g.fg={};g.eg="player_uid_"+(1E9*Math.random()>>>0);var Wba=g.q("yt.abuse.botguardInitialized")||xf;g.n("yt.abuse.botguardInitialized",Wba,void 0);var Xba=g.q("yt.abuse.invokeBotguard")||g.yf;g.n("yt.abuse.invokeBotguard",Xba,void 0);var Yba=g.q("yt.abuse.dclkstatus.checkDclkStatus")||zf;g.n("yt.abuse.dclkstatus.checkDclkStatus",Yba,void 0);var Zba=g.q("yt.player.exports.navigate")||g.Cf;g.n("yt.player.exports.navigate",Zba,void 0);var $ba=g.q("yt.player.embed")||g.gg;g.n("yt.player.embed",$ba,void 0);var aca=g.q("yt.player.getPlayerByElement")||g.hg;
g.n("yt.player.getPlayerByElement",aca,void 0);var bca=g.q("yt.util.activity.init")||g.ce;g.n("yt.util.activity.init",bca,void 0);var cca=g.q("yt.util.activity.getTimeSinceActive")||g.de;g.n("yt.util.activity.getTimeSinceActive",cca,void 0);var dca=g.q("yt.util.activity.setTimestamp")||be;g.n("yt.util.activity.setTimestamp",dca,void 0);var kg,pg;g.og=null;pg="";g.qg.prototype.stopPropagation=function(){this.Zf=!0};
g.qg.prototype.preventDefault=function(){this.defaultPrevented=!0;this.hv=!1};var Hg,fca;g.eca=!g.E||g.sc(9);Hg=!g.E||g.sc(9);fca=g.E&&!g.qc("9");!g.Bc||g.qc("528");g.Yh&&g.qc("1.9b")||g.E&&g.qc("8")||g.Vh&&g.qc("9.5")||g.Bc&&g.qc("528");g.Yh&&!g.qc("8")||g.E&&g.qc("9");g.v(g.rg,g.qg);
g.rg.prototype.init=function(a,b){var c=this.type=a.type,d=a.changedTouches?a.changedTouches[0]:null;this.target=a.target||a.srcElement;this.currentTarget=b;var e=a.relatedTarget;e?g.Yh&&(g.ra(e,"nodeName")||(e=null)):"mouseover"==c?e=a.fromElement:"mouseout"==c&&(e=a.toElement);this.relatedTarget=e;null===d?(this.offsetX=g.Bc||void 0!==a.offsetX?a.offsetX:a.layerX,this.offsetY=g.Bc||void 0!==a.offsetY?a.offsetY:a.layerY,this.clientX=void 0!==a.clientX?a.clientX:a.pageX,this.clientY=void 0!==a.clientY?
a.clientY:a.pageY,this.screenX=a.screenX||0,this.screenY=a.screenY||0):(this.clientX=void 0!==d.clientX?d.clientX:d.pageX,this.clientY=void 0!==d.clientY?d.clientY:d.pageY,this.screenX=d.screenX||0,this.screenY=d.screenY||0);this.button=a.button;this.keyCode=a.keyCode||0;this.charCode=a.charCode||("keypress"==c?a.keyCode:0);this.ctrlKey=a.ctrlKey;this.altKey=a.altKey;this.shiftKey=a.shiftKey;this.metaKey=a.metaKey;this.rn=g.Zh?a.metaKey:a.ctrlKey;this.state=a.state;this.tb=a;a.defaultPrevented&&this.preventDefault()};
g.rg.prototype.stopPropagation=function(){g.rg.L.stopPropagation.call(this);this.tb.stopPropagation?this.tb.stopPropagation():this.tb.cancelBubble=!0};
g.rg.prototype.preventDefault=function(){g.rg.L.preventDefault.call(this);var a=this.tb;if(a.preventDefault)a.preventDefault();else if(a.returnValue=!1,fca)try{if(a.ctrlKey||112<=a.keyCode&&123>=a.keyCode)a.keyCode=-1}catch(b){}};
g.rg.prototype.Dq=g.ca(9);var sg="closure_listenable_"+(1E6*Math.random()|0),eba=0;vg.prototype.remove=function(a,b,c,d){a=a.toString();if(!(a in this.A))return!1;var e=this.A[a];b=wg(e,b,c,d);return-1<b?(ug(e[b]),g.Ja(e,b),0==e.length&&(delete this.A[a],this.C--),!0):!1};
vg.prototype.removeAll=function(a){a=a&&a.toString();var b=0,c;for(c in this.A)if(!a||c==a){for(var d=this.A[c],e=0;e<d.length;e++)++b,ug(d[e]);delete this.A[c];this.C--}return b};var Eg="closure_lm_"+(1E6*Math.random()|0),Kg={},Gg=0,Ng="__closure_events_fn_"+(1E9*Math.random()>>>0);g.v(g.Og,g.mb);g.Og.prototype[sg]=!0;g.h=g.Og.prototype;g.h.jj=function(){return this.so};
g.h.ti=g.ca(10);g.h.addEventListener=function(a,b,c,d){g.Ag(this,a,b,c,d)};
g.h.removeEventListener=function(a,b,c,d){g.Ig(this,a,b,c,d)};
g.h.dispatchEvent=function(a){var b,c=this.jj();if(c){b=[];for(var d=1;c;c=c.jj())b.push(c),++d}c=this.ox;d=a.type||a;if(g.ja(a))a=new g.qg(a,c);else if(a instanceof g.qg)a.target=a.target||c;else{var e=a;a=new g.qg(d,c);g.Wa(a,e)}var e=!0,f;if(b)for(var k=b.length-1;!a.Zf&&0<=k;k--)f=a.currentTarget=b[k],e=Pg(f,d,!0,a)&&e;a.Zf||(f=a.currentTarget=c,e=Pg(f,d,!0,a)&&e,a.Zf||(e=Pg(f,d,!1,a)&&e));if(b)for(k=0;!a.Zf&&k<b.length;k++)f=a.currentTarget=b[k],e=Pg(f,d,!1,a)&&e;return e};
g.h.U=function(){g.Og.L.U.call(this);this.removeAllListeners();this.so=null};
g.h.O=function(a,b,c,d){return g.xg(this.Y,String(a),b,!1,c,d)};
g.h.Va=function(a,b,c,d){return this.Y.remove(String(a),b,c,d)};
g.h.removeAllListeners=function(a){return this.Y?this.Y.removeAll(a):0};g.v(g.Sg,g.mb);g.h=g.Sg.prototype;g.h.rb=0;g.h.U=function(){g.Sg.L.U.call(this);this.stop();delete this.A;delete this.C};
g.h.start=function(a){this.stop();this.rb=g.Qg(this.Gc,g.da(a)?a:this.B)};
g.h.stop=function(){this.isActive()&&g.Rg(this.rb);this.rb=0};
g.h.isActive=function(){return 0!=this.rb};
g.h.Rl=function(){this.rb=0;this.A&&this.A.call(this.C)};var Yg=[],Zg=0,$g=0,Wg=[],Tg=0,Xg={},Ug=new g.Sg(oba,1E3);var ah=null,dh=[];var hh,yh,xh,jh,ih,zba,sba,vba,tba,uba,th;jh=0;ih=0;zba=["server_prefetched_vast","vmap"];sba=[900,60,"waiting"];vba=[500,99,"waiting"];tba=[300,60,"waiting"];uba=[400,99,"waiting"];th=[300,101,"done"];window.yt=window.yt||{};g.n("yt.setConfig",g.tb,void 0);g.n("yt.pushConfigArray",function(a,b){var c=g.x(a,void 0);c?c.push(b):g.tb(a,[b])},void 0);
g.n("yt.getConfig",g.x,void 0);g.n("yt.hasMsg",g.Bb,void 0);g.n("yt.pubsub.publish",g.A,void 0);g.n("yt.pubsub.subscribe",g.y,void 0);g.n("yt.setMsg",function(a){rb(g.Ab,arguments)},void 0);
g.n("yt.setGoogMsg",function(a){rb(g.Ab,arguments)},void 0);
g.n("ytcsi.tick",g.Re,void 0);g.v(Fh,g.Ob);
Fh.prototype.enable=function(){window.onload=qba;window.onunload=rba;window.onerror=naa;var a=window.ytspf||{};a.enabled?(window.addEventListener&&(window.addEventListener("spfclick",fh),window.addEventListener("spfhistory",gh),window.addEventListener("spfrequest",lh),window.addEventListener("spfpartprocess",ph),window.addEventListener("spfpartdone",qh),window.addEventListener("spfprocess",rh),window.addEventListener("spfdone",uh),window.addEventListener("spferror",vh),window.addEventListener("spfreload",
wh),window.addEventListener("spfjsbeforeunload",Gh)),a.config=a.config||{},window.ytdepmap?window.spf.script.ready("spf",function(){a.enabled=window.spf.init(a.config)}):a.enabled=window.spf.init(a.config),this.subscribe("init",xba),this.subscribe("dispose",yba)):window.spf.dispose();
this.subscribe("init",this.init,this);this.subscribe("dispose",this.dispose,this)};
Fh.prototype.init=function(){Fh.L.init.call(this);(window.ytspf||{}).enabled||window.spf.dispose();var a=window.ytPageFrameLoaded||!1,b,c;!a&&g.x("PAGEFRAME_JS")?(b=g.x("PAGEFRAME_JS",void 0),c=function(){window.ytPageFrameLoaded=!0;g.q("ytbin.www.pageframe.setup")()}):a&&(a=g.q("yt.www.masthead.loadSearchbox"))&&a();
var a=g.x("JS_COMMON_MODULE"),d=g.x("JS_PAGE_MODULES");d||(d=[a]);a=g.x("JS_DELAY_LOAD",0);0<a?(g.xb(this.B),this.B=g.vb(function(){b&&g.jc(b,c);window.spf.script.require(d)},a)):(b&&g.jc(b,c),window.spf.script.require(d));
dba();Qaa();Laa();gf(!0);g.Qe(!1);g.x("SERVICE_WORKER_KILLSWITCH",void 0)||"serviceWorker"in window.navigator&&"https:"==window.location.protocol&&(g.Oc("service_worker_enabled")?Dba():window.navigator.serviceWorker.controller&&window.navigator.serviceWorker.getRegistration().then(Eba))};
Fh.prototype.dispose=function(){g.xb(this.B);var a=g.q("ytbin.www.pageframe.cancelSetup");a&&a();g.yb(kg);if(a=g.mg())a.removeEventListener("onReady",lg),a.removeEventListener("onStateChange",lg);gf(!1);Fh.L.dispose.call(this)};
Fh.prototype.disable=function(){Fh.L.disable.call(this);window.removeEventListener&&(window.removeEventListener("spfclick",fh),window.removeEventListener("spfhistory",gh),window.removeEventListener("spfrequest",lh),window.removeEventListener("spfpartprocess",ph),window.removeEventListener("spfpartdone",qh),window.removeEventListener("spfprocess",rh),window.removeEventListener("spfdone",uh),window.removeEventListener("spferror",vh),window.removeEventListener("spfreload",wh),window.removeEventListener("spfjsbeforeunload",
Gh));window.onload=null;window.onunload=null;window.onerror=null};
g.Sb(new Fh);})(_yt_www);
