/* JS */ gapi.loaded_1(function(_){var window=this;
_.Uh.prototype.Xr=_.M(13,function(a,b,c,d){return _.Eh(this.Va,String(a),b,c,d)});_.su=function(a){if(!_.Ka(a))for(var b=a.length-1;0<=b;b--)delete a[b];a.length=0};_.tu=function(a){_.Ed.call(this);this.wa=a;this.T={}};_.B(_.tu,_.Ed);var uu=[];_.tu.prototype.va=function(a,b,c,d){return _.vu(this,a,b,c,d)};_.vu=function(a,b,c,d,e,f){_.Ka(c)||(c&&(uu[0]=c.toString()),c=uu);for(var g=0;g<c.length;g++){var k=_.O(b,c[g],d||a.handleEvent,e||!1,f||a.wa||a);if(!k)break;a.T[k.key]=k}return a};
_.tu.prototype.yb=function(a,b,c,d,e){if(_.Ka(b))for(var f=0;f<b.length;f++)this.yb(a,b[f],c,d,e);else c=c||this.handleEvent,e=e||this.wa||this,c=_.Ih(c),d=!!d,b=_.xh(a)?a.Xr(b,c,d,e):a?(a=_.Kh(a))?_.Eh(a,b,c,d,e):null:null,b&&(_.Qh(b),delete this.T[b.key]);return this};_.wu=function(a){_.He(a.T,function(a,c){this.T.hasOwnProperty(c)&&_.Qh(a)},a);a.T={}};_.tu.prototype.Fa=function(){_.tu.ma.Fa.call(this);_.wu(this)};_.tu.prototype.handleEvent=function(){throw Error("N");};

var Yx;Yx=function(a,b){return a>b?1:a<b?-1:0};_.Zx=function(a,b){a.sort(b||Yx)};_.$x=function(a,b){_.Ka(b)||(b=[b]);var c=(0,_.xd)(b,function(a){return _.t(a)?a:a.To+" "+a.duration+"s "+a.timing+" "+a.Sh+"s"});_.Q(a,"transition",c.join(","))};
_.ay=function(a){var b=!1,c;return function(){b||(c=a(),b=!0);return c}}(function(){if(_.N)return _.ef("10.0");var a=_.Mg("DIV"),b=_.Pe?"-webkit":_.Oe?"-moz":_.N?"-ms":_.Le?"-o":null,c={transition:"opacity 1s linear"};b&&(c[b+"-transition"]="opacity 1s linear");_.Ls(a,_.kt({style:c}));a=a.firstChild;b=a.style[_.pd("transition")];return""!=("undefined"!==typeof b?b:a.style[_.qt(a,"transition")]||"")});

var TG=function(a,b,c,d,e){this.width=a;this.height=b;this.R=c;this.S=d;this.opacity=e},UG=function(a,b,c,d){return new TG(void 0==b?a.width:b,void 0==c?a.height:c,a.R,a.S,void 0==d?a.opacity:d)};TG.prototype.equals=function(a){return this.width==a.width&&this.height==a.height&&this.R==a.R&&this.S==a.S&&this.opacity==a.opacity}; TG.prototype.interpolate=function(a,b){var c=1-b;return new TG(Math.round(this.width*c+a.width*b),Math.round(this.height*c+a.height*b),Math.round(this.R*c+a.R*b),Math.round(this.S*c+a.S*b),this.opacity*c+a.opacity*b)};
_.VG=function(a){_.du.call(this,a);this.Ma=new _.tu(this)};_.B(_.VG,_.fu);
_.XG=function(a){var b=Number(a.W(200,"widgetWidth","width")),c=Number(a.W(100,"widgetHeight","height")),d=a.W("auto","corner"),e=a.W({},"menuCss"),f=a.W(!0,"hideOnClick");a.Bd=!!a.W(!0,"hideOnLeave");a.Lb=!!a.W((0,_.ay)(),"useCss3Transition");a.nc=!!a.W(!0,"allowOffset");var g=window.document.createElement("div");a.S=g;var k=_.iu(a);k.parentNode.appendChild(g);var l=window.document.createElement("div");a.Aa=l;g.appendChild(l);e.position="absolute";e.width=b+"px";e.height="0";e.border=e.border||"1px solid #aaa";
e.background=e.background||"#fff";e.zIndex=_.ku(a);e.overflow="hidden";e.boxShadow=e.MozBoxShadow=e.webkitBoxShadow=e.boxShadow||"0 2px 2px rgba(0,0,0,0.3)";_.Q(g,e);_.Q(l,{left:"-1000px",top:"-1000px",position:"absolute",width:b+"px",height:c+"px"});a.Kf=g.offsetWidth-b;a.Lf=g.offsetHeight;e="auto"==d?["top","start"]:d.split("-");k=_.It(k);a.vb="bottom"==e[0];a.La="right"==e[1]||"left"!=e[1]&&k;a.T=WG(a,b,c,"auto"==d);a.Ib=_.r.setTimeout((0,_.u)(a.jd,a),500);a.Ma.va(g,"mouseover",a.hK);_.vu(a.Ma,
g,"mouseout",a.gK,!1,a);f&&_.r.setTimeout((0,_.u)(function(){this.Ka||this.Ma.va(window.document,"click",this.kL)},a),0)};_.VG.prototype.open=function(){_.XG(this);this.Ca.ke(this.S);this.Ca.Lc("resize",(0,_.u)(this.resize,this));this.Ca.Od("showMenu",(0,_.u)(this.eC,this));var a=this.Ca.methods;a.setHideOnLeave=(0,_.u)(this.oz,this);a.displayStateCallback&&(this.Kc=a.displayStateCallback,delete a.displayStateCallback);this.Ca.Ie(this.Aa,{height:"100%"});_.YG(this,this.T)};_.VG.prototype.open=_.VG.prototype.open;
_.VG.prototype.$c=function(a){this.Ka||(a=a||{},this.Aa.style.left="0",this.Aa.style.top="0",this.U&&(_.Rg(this.U),this.U=null),this.Ib&&(_.r.clearTimeout(this.Ib),this.Ib=null),ZG(this,(0,window.parseInt)(a.width,10)||(0,window.parseInt)(this.Ca.width,10)||this.T.width,(0,window.parseInt)(a.height,10)||(0,window.parseInt)(this.Ca.height,10)||this.T.height))};_.VG.prototype.onready=_.VG.prototype.$c;
_.VG.prototype.resize=function(a){this.Ka||ZG(this,(0,window.isNaN)(+a.width)?this.T.width:+a.width,(0,window.isNaN)(+a.height)?this.T.height:+a.height)};_.VG.prototype.close=function(){this.mb?$G(this):(this.Ta=!0,aH(this))};_.VG.prototype.close=_.VG.prototype.close;_.VG.prototype.W=function(a,b){for(var c,d=1,e=arguments.length;d<e&&(c=this.R[arguments[d]],void 0===c);++d);return void 0!==c?c&&"object"==typeof c?(d={},_.ot(d,c),d):c:a};
var WG=function(a,b,c,d){var e=_.iu(a),f=_.Yt(e.offsetParent);f.right-=a.Kf;f.bottom-=a.Lf;if(d){var g=e.offsetLeft;d=g+b<f.right;g=g+e.offsetWidth-b>=f.left;a.La=a.La?!d||g:!d&&g;g=e.offsetTop;d=g+c<f.bottom;g=g+e.offsetHeight-c>=f.top;a.vb=a.vb?!d||g:!d&&g}return new TG(b,c,bH(a.La,e.offsetLeft,e.offsetWidth,b,f.left,f.right),bH(a.vb,e.offsetTop,e.offsetHeight,c,f.top,f.bottom),1)},bH=function(a,b,c,d,e,f){return a?(a=b+c,Math.min(f-a,Math.max(e+d-a,0))):Math.max(e-b,Math.min(f-b-d,0))},ZG=function(a,
b,c){a.Ca.nb().style.width=b+"px";a.Ca.nb().style.height=c+"px";a.Aa.style.width=b+"px";a.Aa.style.height=c+"px";b=a.nc?WG(a,b,c,!1):UG(a.Wa,b,c);a.T=b;a.V||cH(a,b)};_.h=_.VG.prototype;_.h.oz=function(a){this.Bd=!!a};_.h.hK=function(){!this.V&&this.ra&&(_.r.clearTimeout(this.ra),this.ra=null)};
_.h.gK=function(a){if(!(this.V||this.ra||!this.Bd||a.relatedTarget&&_.Wg(this.S,a.relatedTarget))){var b=_.Zt(this.S);a=a.clientY>b.top&&a.clientY<b.top+b.height?0:300;this.ra=_.r.setTimeout((0,_.u)(this.Bb,this),a)}};_.h.kL=function(a){_.ju(this.S,a)||this.Bb()};_.h.eC=function(a){this.show(!!a||void 0===a)};_.h.show=function(a){a?!this.Ka&&this.mb&&(this.V=this.mb=!1,_.YG(this,this.T)):this.Bb()};
_.YG=function(a,b){dH(a,UG(b,void 0,0,0));_.r.setTimeout((0,_.u)(function(){this.V||(this.T=b,this.Lb&&_.$x(this.S,"width 350ms cubic-bezier(.23, .50, .32, 1),height 350ms cubic-bezier(.23, .50, .32, 1),left 350ms cubic-bezier(.23, .50, .32, 1),top 350ms cubic-bezier(.23, .50, .32, 1),opacity 350ms cubic-bezier(.23, .50, .32, 1)"),cH(this,b),this.Fb(!0,!1),this.Ba&&(_.r.clearTimeout(this.Ba),this.Ta=!1),this.Ba=_.r.setTimeout((0,_.u)(this.Fb,this,!0,!0),350))},a),0)};
_.VG.prototype.Bb=function(){this.V||aH(this)};
var aH=function(a){a.V||(a.Fb(!1,!1),cH(a,UG(a.Wa,void 0,0,0)),a.V=!0,a.Ba&&_.r.clearTimeout(a.Ba),a.Ba=_.r.setTimeout((0,_.u)(function(){this.mb=!0;this.Ta?($G(this),this.Ta=!1):(this.Lb&&_.$x(this.S,""),this.S.visibility="hidden",this.S.left="-1000px",this.S.top="-1000px");this.Fb(!1,!0)},a),350))},$G=function(a){a.Ka=!0;_.Fd(a.Ma);a.Ma=null;a.ra&&(_.r.clearTimeout(a.ra),a.ra=null);a.ua&&(_.r.clearTimeout(a.ua),a.ua=null);_.Rg(a.S);a.S=null;_.Rg(_.iu(a));a.Aa=null;a.U=null};
_.VG.prototype.Fb=function(a,b){var c=this.Kc;c&&_.r.setTimeout(function(){c(a,b)},0)};_.VG.prototype.jd=function(){this.U=window.document.createElement("div");this.U.style.width=this.U.style.height="100%";this.U.style.position="absolute";this.U.style.background="url(//ssl.gstatic.com/ui/v1/activityindicator/loading_gs.gif) no-repeat "+(this.T.width-19)/2+"px "+(this.T.height-19)/2+"px";this.S.appendChild(this.U)};
var cH=function(a,b){if(!a.V)if(a.Lb)dH(a,b);else{var c=(0,_.Ta)()-20+350;a.ua&&_.r.clearTimeout(a.ua);a.Zb(a.Wa,b,c)}},dH=function(a,b){var c=a.S,d=_.iu(a);c.style.left=a.La?d.offsetLeft+d.offsetWidth+b.R-b.width+"px":d.offsetLeft+b.R+"px";c.style.width=b.width+"px";c.style.top=a.vb?d.offsetTop+d.offsetHeight+b.S-b.height+"px":d.offsetTop+b.S+"px";c.style.height=b.height+"px";_.Ft(c,b.opacity);a.Wa=b}; _.VG.prototype.Zb=function(a,b,c){this.ua=null;if(!this.Ka&&!a.equals(b)){var d=(0,_.Ta)();d>=c?dH(this,b):(dH(this,a.interpolate(b,1-Math.pow(1-Math.min(1-(c-d)/350,1),3))),this.ua=_.r.setTimeout((0,_.u)(this.Zb,this,a,b,c),20))}};

_.Sn["slide-menu"]=function(a){var b=new _.VG(_.qP(a)),c=new _.pu(b);b.open=function(){};_.XG(b);a.attributes={height:"100%"};a.where=b.Aa;a.onClose=function(){b.close()};a.onRestyle=function(a){if(a){var c=!1;a.hasOwnProperty("showMenu")&&(b.eC(a.showMenu),c=!0);a.hasOwnProperty("setHideOnLeave")&&(b.oz(a.setHideOnLeave),c=!0);c||b.resize(a)}};a.onCreate=function(a){a.Ec=function(){return this.bl("openerIframe")};c.Ca=b.Ca=a;a.ke(b.S);a.register("_ready",(0,_.u)(b.$c,b),_.Cn);b.Kc=function(b,c){!a.Xb()&& a.Jj([b,c])};_.YG(b,b.T);c.open()}};

});
// Google Inc.
